// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9+XMbN/Lvv4Lv7FZZSsjR4ePFepXKU+RjtbFjrSR7q57lTYEzTRKrGWACYCgxXu3f",
	"/q1uAHOQQ4qSZcVO+IvNGVyNRuPTBxqjj1Gi8kJJkNZEex8jk4wh5/RzvxDvQBuhJD6lYBItCkuP0f7R",
	"oS9jKQyFBMPsGNjEvYOUuX6YGjI7FoZpKDQYkJZjB/iaS6YG/4bExuwENDZkZqzKLGWJkhPQlmlI1EiK",
	"36reDLOKhsm4BWOZkBa05Bmb8KyEHuMyZTmfMg3YLytloweqYmL2WmlgQg7VHhtbW5i9ra2RsPH5dyYW",
	"aitReV5KYadbiZJWi0FplTZbKUwg2zJi1Oc6GQsLiS01bPFC9IlYiZMycZ7+RYNRpU7AxFEvAlnm0d77",
	"aLLDs2LMd6JeNMzEaGwTm+Fo1fsPvchOC4j2ImO1kKOoF132sXV/wrXkORjspl6Pd3WH9csXoetD9a7R",
	"8WV/pPrt3q960QG3PFMjXFi45HmRAf7kjRVfQGovOhcyjfaqHnpRDpan3HLsAYmN9iJIR9DnRWFwLFNA",
	"QhIkTJHx6c+uyvN0BGy/KDKRkEyY6OqqFxVaFaCtADNLz8forxqG0V70l61aYre8YGw1ZPUqkDgrsz8J",
	"mTJhGGeOD04matHEVyhdx89PTllYSCe+TlLrqqYWWhQ4IYegXc2hVjn1AjItlJCWHpJMgLTMlINcWNwN",
	"v5ZgLMpzzA64lMqyAbCySLmFNGaHkh3wHLIDbuCziyzKhukjy0ho50SlubzLlmCyMwDLd35RBUheiF/e",
	"EM9eg+VNIVjWgxepE6yKTSy3pVm1kauMMoTcFRpS3DMNCfJi0ZiQp6refW6ZG/vj0EI+L0iNwoZIIKLx",
	"Wp6ZhbxAoHIiwVniWsXs0LJCq4lIwSB48jKziHlDMSq1a+rAitkxtyzhEmUjKY1VOUHZxRgk42ka5LU1",
	"qGKcDTMAi2v51eymT5G7xmrcQtiwmRO4u5ecfW3FkCe2Q31Kxn0h0zAEDTKBmJ2OgWGHbCggI+4iB1OB",
	"TXMhuVXaKbnSOMCQ4tcS2IWwYyGdLPheDcuE6ZABh8+z5LyhHzxj4zLnsq+Bp3yQ0ciI2AxbsaHyEBfG",
	"IBUXlEf0j4M3/9xlz4Q5Z4c5H0HXkroXK69L4N8pNrvqRaUWHawMfHx7fEicUKUNdgj7teSZGArQjrfh",
	"dcVytmH5iCnNUjECYzdJoHE7Qcq4JbHNSrexRA7tCf9a8ikCsIZ0zO2WHkPWHyhlk/6vibrYRXER8hXI",
	"kR1Heztz3JgRNyp1U1xRqk49MxewY6h0zm1beGL2elXJYYcyyUqEKDcngWvaH5QiS0EzVdqiDGO0bB1U",
	"QlxI0FEvCnzguYh6kTAKf0ueKJnyvnuc5Ok5/jfG7aX5RdSLRgkgC2pGN7tcwUxawKqDRi8LqvzD07ug",
	"eJ+msaDwkKazqKWf9NJK7xwrFpUShxYUHhPjFhS+RH62ReiAWxgpPXXiQxoo2osaeiTqzas8akGWe1Bl",
	"TFjIm4tvpgYVZq/V1YebrloY6yT01lG23xxgZnJBlQ6yjv1x0FK0hLNtRYvAjpBBAIATZBmaUmyDV9ra",
	"bBIKqwloLdIUtXENOVQ7Zl539F1jr9CHZZahe1JkPAHqvF2+gYZgDnoE6eY8djsbgTR5mgqH2EeNGlaX",
	"0Fs63TAMyMk7rk2PFUpb02MTlZU5mF6lp02PgU3izRbifYx8O/z56s3LX149f/f8VbQXoW2KIEW94WI+",
	"3X66vYf/0NrMgZmbyAkB/s2m8/eTNz8z19D5nWhlJI0FZwXXPAeLljmukR2D0DhvkRILGpZGTQ/quy61",
	"+AwsFxmkLFVJmQfntccK0h98kKHlz3Kuz1N1IT0adtgyV8sB/RnaQV6WO2ioCskHwCFIctEUaG1EVGNe",
	"CGN2RJYVCplMcZ+Qqel6QneajOV5CcvBGFTdc1Qce03FfA0Gl0XGHfsvxlNnF4jWGMj9C9xXVrFUMSGN",
	"BZ62VegpNUPaW21j9tYAkyMhL/tFVppm4zmbwu8mXJ4lhg1ZMBSMANZo0WbgRmNHKplN2+If1QRF12nz",
	"wMhrVPkrYexS9wIrOCMblTJOoFFo7s7Ex4mbeUpeLRi0qr6iIVfbfhHXmk/XPvoX4qPjAjun6WbejxOA",
	"a6SbOkahzLI3w2jv/SeEDz7OqsI6fNWWH7Tyw562FboMIFNy5JbyROQi4xphiYyPglSxZD+VA9ASrA/d",
	"Vbu+DmVdt+kDUfNs+TCrx157VhKMt8MJIX7Inl9akKlhNSPIXK+mZxJVCDnq1Gizzu0yjMEKrSBuOxYx",
	"r2g6YCf4Dkv8EaeuSaJrV7LVLXtGRKRMyQT+77yzZpw/NgEGPBnXDrSQKRQgU5A2m8YMbd4lHnLwi6sV",
	"fv8x8K/paJCvWfl4hVY52DGUpvGT1vWmUFjFBK7IPzx0zXfm8TFp2Ogr9l2Z9Ve9YNbfhLSW4UxdtOyS",
	"FXtpWjPYSTPoOyscf1sSbjBjtKmErGQEF07IUTcAtiy0tzrr0mXyHDc9XPpDg1aTzk7HKoei0x5CmAml",
	"7O3xKy/R0LYnCq3ogKOrb5F0WXvYldKMoOHt8WGwWFq9YksaL7BLSPb2sHMQH2bU8wMd+RIcrSgHmTBj",
	"fOgYbgOXm8sp1rTAc1qdzc7hzFhp+6w5zhwasIEWMGRKQj8TElijuGv07mHKAj2NxUvsK9RgSjxtLjfx",
	"bwSW7IkxZEV8B+GqEKbywNUFhhMuMhL1UIeVBkk4EDIRUnIrWK5S9B/RAvaGqsPLQouc6ylDfdRj5lwU",
	"xkWCjaUekzGXEjJfQkdjOaSC23qwWdjzTchlc71EvWjIjUUVVsOu9z09NO5FZsx3Hz/Z4w8hffo44TDY",
	"3h0O4cl3SZo+HabfPXq0/eTJd9scnj5Mnzx8mAx2njza3U23t+E7/n+S3d2njx8PHj1JHzWMdxPtRbvx",
	"o0fxdtSLaAJI0m786GG8jbRMqkOp3fjR43ibLIIm9dcTPfH9zw36kAZtjUD1boHtDYO6jebdsb5aazZk",
	"5hqbqjvoRypPDdsb1+s8tGWDLmnGahQOOxQ6v+AaqUm1mJDma2rBMWR51EM1mGZgqTAvlKH6aAneOLaD",
	"lL45iebm9KImZKbkWaBr5v2CeB4W/c1RPfP2H9Uk5noKc5odmqbYXoCGe7WaXbtYwc4ZtZVAz1lrvsQZ",
	"TcEwali1TZ9s3jlYZmbciZJvb7vucM7H5eHwOQuZFxRrDEYeHYtYxSgOzVpR+5j9BFPjTL6cWzQNXXUh",
	"KZoXVxstZm9kNmXnMIW0EfDmGhivoLkyTkMwpR0D+xxIGELlDqYcwCG7mvzb6QxcBSRbVRpPSII7PBK0",
	"aFAV1brJe9Wy1kO9OuaGijpopLIYaZ4CaaaYFPS5KI65dIbTTehyjeaJO4F8ApppLEapqLRnFbgNNKRC",
	"Q2KzqcsUcfQ7ZYrL+lvfWI02jPPiyS4YKzsUl7Ne31m5vf0Qvt+Jt+NtRg/JTvzQLYxXUHPKvRL7W9G3",
	"oi5HTddXKMXdWj0ikqNetBPvOOW5khYLcjEPEJObAt5CETuBnEsrkkrABLpsdDzHNiAexT22E+/GD3ts",
	"F+fQ18nOZsyq0OOwjm8ypVOg8BCXacXbkebFuL2MYTfNKOBJFdqoMLcFYit48Ps1LbMnImyoskxdhG0y",
	"a9vhSuvaKDuTCD9SpYArzRqyQvOhGQYqCakyPsCftEGV8U3jM/m2sQ1dzdT704NpbUpuuE2+GUzIjbzM",
	"rCjojdJnstq7bMM0dt1m40BwgUZrHqacSX840jrlCD5pfCaXBC2WBkUXBkTvPRh640DoOgj6ZwuCLg29",
	"+bAblgw6A29NXIkrqaONXdkgzjXMVMKzbNrPueQjSK85I7iniMztAhz3Ftv4vcIav2dEY8k55EmVa9ct",
	"rFTcTHajKZVaE1q40pYidHR2HmI7M6lrsEZ/MLtgdYcrge7sJj8I417rnTco7Nrb3ryZI/421k3LVqFS",
	"5Be3FjR2+a+N7f+83+k//XB2ln6zeXYWL33e+GGvv7Hxw17j3X/wn/e8/9t+///3P7zf7j8Nv6k69rBy",
	"/c1vNjd/oEbfbjRLvnUdtV5R3b92put0JSM3jf8uvta2f6KksZqjtvI87TDUib+bMTspeAJ9AwXXdCKN",
	"VrTpucMDOklR4XQYBZSS6zZ8d77fJPyA8KLHvu+x//bYvza9lefMK97pLEaLiGuv8ntfzVX4778+fIPM",
	"/PCt5+qHbzeqX5s/bPRrTsd9enN29u3cO/YZOt385gZLugBPPJCQcaPBltonpRB8oRbzPlOq5AMbaihL",
	"AE5b8A7tvESlXfJWjkZgUF7+dnp6FEjAunVkwAFej20zMWRoExmXb+vSMygjxj7crZmFHtzIuVdri+9O",
	"Lb4F+Sr7c5ms8wq51lqOj4QBi46CNHDTrflznoyFhIVDVekx1QC40P4w8ix6wUVWajiLQlIOO/QEOREQ",
	"hkFeWOwDvUZhmFStRKAqcBWzfXZMZLIk4xo1D+Wkkxj7yZIYD0rcX2BIcht+Wrdpsnwje17WzGNvJKru",
	"PXYWnZRJAsacRWisNGb62cXGFJD0uUz7dZ7T8pP7LkPfT9zDRCUBvaW5PYutjlvnQVRd/MhNV9R4lUOq",
	"hX26I6uu44kVQiBVL8EfMSyljDnnlSgJjONS2MqUm7fvhGH7R4fsGIJ5t4yJxIE5ScS3rDLaEEBLkoxG",
	"GKbO7aDRmuLiYm9oDdDy0AWKNEUgdnmgiQslgyw78h4ybuyp5tI4Zop8wVEx1qMM8uDmeVpt1RZSB8/I",
	"NL9XkRJJqq+lWhCH+9jXjQCR/DpWYVRI4/PZgcijsHR8oErrKa7I64QGNTCoaNKXIP3u7559HHzmeFTV",
	"dFq+zY0LblCRsgE3kLKycMM2deqTR506dTE4b5BftslcjfqUPoz5wKw009VuIi2U2wV3kyqE6RCjT8Wb",
	"k5Vgu+JDjwRPDdmpLqHHXvDMQI+9ledSXcjmqSGWR72IKkS9yNdY9RywTZ3va+Zt6HrmdTXSsllfczpa",
	"SZpoGjGN2e0XhVYTQPg/PXr9DkiJpnTLsip4BtK9e0G5wfNVSekJd5jeegggd8S1oaonU5nQj3c8E/j/",
	"MSJWaQ/lkVYjDQaF4y1aXo6lJwUkoeprH7Z9cyFBG6JrIhJ4Bqg9hUFd5hr9qJRNUKb0gcqLTHBpV1yu",
	"51KrLMtB2mNnFDa4MFfWZsIBYuSQEo9PxAgpme9iYZ2KwwtrVKxfWKNNzjEUygir9LRzQXAdFhbMrVqz",
	"sFrBFxmADWtDD11r6daosaLuRXNd3ZuVV9e971zjjo1SRTo7g9uUYlhHJANqO6g2U2nHYEXSiEHRieuY",
	"T6DHBB0OoB7JhLEu937CtVClqQxt77+x/dqDQQ8FO6B064BBH+uMxx4LhF11hpKskGXHjn/Np3SVAyw6",
	"aIh0pQFNz5xlIhfWHZ8Ak2U+cMFBiip5dw9Sd5m8Tp6v1BWpPM3G3LAcrVjiUMMGp2tmwXJXBf+1hOpe",
	"+oDoSOkY2xgqcK6td7rC9faGf4acJyXrbCU69LAKydQCJs6ekHBJHigF4Kpj7IrdB45NdFpGARRhLFph",
	"1BeS5V28Qjn5DyzzM20HpXHeyZjLEaRo1RML7JhLxtkQLlguZInsojUtuDHoMp5Szr1b8fDRAHfBMXDb",
	"HX66VCiXF+qX1rPyQmQZkuhCagnPAqc8p91aDoU2FCItlET1VcoMjGFTVTp6NCQgKlZadQ7S382VDLTG",
	"6ThVu8ADzN2FB3fuVXZdNzhtSZQpBwYXVlovXI0MVHYxFpTDCsR+t30gdVXCQoepeJ8QwlsnLOEQIHUn",
	"grgcjqsGMkjQZepho1k5r+YRiDKsdLo1XJjx3QSmZzC0rJS0eWTKVC6shZSlJQUqDGjBM/Gb9/6ahNI6",
	"5kUGFtgGCJL0ASS8NOhtOlfWsmRcynPsSdWl4TqJDbYzVdqs56PBs85J4Oyc3ESE+ZSZhCCKoguPJOOT",
	"nXjnMUtVCPk0xnBSjjapxGXESVS3TWblBmf2DRgrclID37jdJn4DH0FXGa4fEXFAwZnqyxg4rgZCykV9",
	"WxWQT2n/AJf+su61pvTVCiZmIy9//rpNnaouZhUIzzJW4O6n2FqnEnF7QoRzZmzhUYzw29dNNHDbcbJA",
	"sSpeHS0sykK6Ju+orux8kWmFhSKBzlx7osfb7cbyvOjGhcr98wE79HbcVNLV/bsUMrjNWH4DUPObjDda",
	"4trtM4duSYUurXBlw4NuuH1+U6RgKKeDIgExO1JFmVGMPvCbrn7G7Bh4StkuK3qCLjdiaRIavwxJaE8e",
	"rpqF5oOy5zANls3c9xmCYld6xCXuZcrbcHmX+LhhElW4tw6fN5sB7Tmh6r6nT/qlcZPNf0AHncR6WruP",
	"u+alLmTXqdV+M5rMLVMX0oQv9rj3aNuxM4qKbeHYZ9Hii46oJVt6vvPLB94q8kylYauzMtMwPR6Yxhd+",
	"Gsk2sjHvFU44ZwHsiNtk7N0EpK86TuwWmSH5wjNYoxZsvDrGaxWiHXKq6WDylO65u2Qc+pWrCe08MB1u",
	"2RWdE427lo1uwh4pYhDDSp3LQYLaTaoznXy4S+mQIRTPhSlUEXkyuiIQc0epBpJSCzulW7qOWwPgGvR+",
	"6Wbinl6Ezfz3f55GPffZKezIldZzGVtbkPzq0WHaPZO3bw+fVTvCbb9GjMlLdG2Cxuw1L3x4rVW/1lgx",
	"CjodNUu6BAR6GoU9iZT8Qq5amHohfgKc+1XP3YQOSaLuwx+oorNoL7LA8//X/KZS3SNOwn29iYx1rTJ2",
	"CjynW0iZ54HZ29pqtZ7DqvftLj5sdDXb9KdMTp+5VAtIMo5SO0F/TPKRuxmrhu47MhQsgnSEoI1tmveq",
	"L5Q+zxRPTXwmz+RpiOaGzboRvhq1WUeI6UXfWD6ChhHgLAQNaDOTxrLKuxkuVywTCUgX/PU82y94Mga2",
	"S4epbTZdXFzEnIpjpUdbvq3ZenV48Pznk+f93Xg7Hts8I/EVlk5qZ9i/f3TYuhRQff4KJdHhSLQXPYy3",
	"4x2/OUjQt3yyQgUpI7ALEsmaOTqMJ1oZZ/A0s8sqNEHJp2b7WdZsSGOH++50stABtv6Mu6qIvCWRDraz",
	"KTPbOB104Nv0ZP3eqntopFrb2VoPgu/2IHzFRvpsYZhQOKDt2izYZJVv76GBd5huV70uk8T5Ps5JxpqJ",
	"rT0Scn+8yxksS2dxCO3zKukWImUp0mWxCeipHftrll2EUqsTP+o9UuuSLXshM4gcKJ/FgCw+B/bg+wc9",
	"9uB7/Bd37IP/+f5BlTQRncN053tat53eOUx3/8c97J5Fm4tmSiPebqYoSjm/FHmZtzxRJ3nVJJv+ce37",
	"ntaxCLJjneO1WNBazZkYtsUcLunrNqcu+t0MMuR86vzL9kdATEPuhUTsrN164tBCyRC5sC0+zaUHeJ5E",
	"ezvb29uU8e8etztcM7rd5CZF0LK7vR00jf/0QeOjK1v/9gci9eAr3uyg7FvSZTOu3U+IfY/ucNDqVGRu",
	"rB95yoKBRoPu3MOgbyUv7ZiM9dSN+vAeRn2h9IA+IUND7j69hyFPlWKvuZwGFtM3Gh/fy2xPvNnxVlZx",
	"Smez85Fp3aC/6kWX/WAeoDpo6tWrXqVoV1OyrPVVznmtGnTu76BO19p0rU3X2vQPqU3XmnStSb8ITVqo",
	"zgtVFHtmfE5JzutIV7X+4LM/gfpRpdO73jRurnX4yeoSrub26s7nGbaLQSlFH+Q5jdxiRPg2cJtXyVyV",
	"tlHR+HYREuZheaDS6V+2QviJ4qy0nM8oYN/4WHd7sLRVPDuQR87rR3kJduEQo7rsDvqv05IWjXISkqJu",
	"OVbDnjsMUZj2WNlsjU9ZoGMXNV3IPt0uv/W02uMsYqPuqnXLMa/WSupzK6nt+1BSB0oOM+GC9Wu1eI2D",
	"2XYutz76X1dbN43o+m++H9SX/ha6nStFcmdP/rqUdvc368iYpuOb2h1safJa0d7M3/oEZ/iLc1Pv3h39",
	"FCdtHVBca5g70jCP7mHIn5VlL1Qp07WKuZXnRR/+pGDIQnVxcI1X8eXpiw+f1U10HxXukIt6qq3PqdJ5",
	"cpU3du/u5SJyO1zMlsfX7WKmc1WWejC0CDGliNQLeQvfrZuYUbv8M1LSdoG6qdHzdT4bRWsH6Y+ovu7d",
	"J/tKHKOt+bO3Wfdo6yPujCun8BCiuv6aAWWDt1Xfdb7Ss2vw7itwlhZQ1NJRcff49N+NNe9nsusXC9ja",
	"nP9D4uGXh06dAZiXdLPrJqDycpndskaUe0OUayzkNaysYeV+XHVuk45E+yP/PeHVXXVq8YeHFrrfgDO9",
	"U4xZNV7Qp6G/vZmcLL0HstKx8xr11qi3di4/EWdL2/Xn5dxfRLwJzh5fF+pZG3FfeEC2unH2xSHv7xAC",
	"XuP9Gu//3MHEGwcPl2QsPluSGHdjvUB/wZQ6XIfo1iizRpn1Gf/N4pFLcOrlouzaW4HUyH2F+CsJ+a0h",
	"ap0U9KdMClop0rgENJoRxruAjXUcbw1layhbW1tfBXh2hQ/pg6qrOYbHy+7j3Ao93V9G+DqidF8cPN7z",
	"Vb41IK8BeQ3I936LiiJ7W/VH9Be6zM0/JHYT57nzpuOtzn/WvvMa39a+89fpO98MPZpe9BeIH2sXeo1o",
	"a0T7czu0NwO04+s//vB1QNrX79auIWvtZK6dzM/uZNLXxumvdBC0ua9Ab/FCbE126O8V+r7m/kxFwE3D",
	"lOz+SORMlt/Vh6v/DQAA//+Vz3HdKacAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
