// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9iXLcNtco+Cq4/d8q27mt1uI4f6yq1Dey5EWOtUSLHSvy/EGT6G5YJMAAYEutlKvm",
	"HeYN50mmsJEgCS4tS/LG+qq+WE2sBzgHZz//DgIaJ5QgIvhg898BD2YohuqfW2NOo1SgQyhm8u8Q8YDh",
	"RGBKBpuDI5QwxGU3AAmApi2Y4AiBBIrZaDAcJIwmiAmM1HiJd5yTGcp7yyZAUAD1OJQAMUOAL7hA8Qjs",
	"U4GAmEEBIFkAdIW5wGSqm17iKAJjBOgcsUuGhUBErgBdwTiJ0GBzsDqHbDWi01WYJKOITgfDgVgk8gsX",
	"DJPp4NOn7Bc6/ogCMfg0HGwlyYn6zbds2RrQiVojTJIIB1B+VfOSNB5s/qWBy9HgQ3m24eBqRTZamUNG",
	"YCwh9Jedbdt20guw425TIhARci0wig4mg82//h38b4Ymg83Bf63mx7hqznD1BY6Q7fRp2Nz2CEVQ4Lk+",
	"bNmYoX9SzFAo16VO7kMFPKX1PSfzt5Dpoy4cPMo/wDDEsi2MDgtNSkcxLEH7OZljRkmMiABzyDAcRwhc",
	"oMXKHEapvDaY8SHARK4LhSBM5TCApUTgGI2APKwLtACQhED3QDCYgTjlQt6ZMRKXCBGwrhpsPHkMghlk",
	"MBCI8dGgsu2ae2LBcMjoHIeIHSco6H5WHjjKUygCEua3sWUs1ezTcCCvVg3O5RMC2SqDxvr/9//8v0UY",
	"gIiS6RBwAZkAl1jMAAQREgIxQBkgaTxGbKhgF1AiICaAUHA5wwLxBAZo1AnV/h1QgjoAajeGU1QH7rZb",
	"vksiTOp7f/j0oflsjwUUKfdTBP1N0gMIOCbTqAhjQ8tCNMcaJJZEHDKUQEMTjiWI9T+PUkL0v54zRtlg",
	"ODglF4ReksFwIAlEhAQKu9OV4g7cOSsfnUVUvuWrqnyyy6x8yNdd+eRspAjotzRK9c3N0acI7h00wQRx",
	"ANXtDcFc9QApRyEYL9SbVCTJRVTyI8Ypwf+kSOODIezuuPLuY+Kj99X77dJPNdmHz7zzGiSVC+uDW5kE",
	"Fbeud8Sru3+DuVD317m2prHcIxYo5h1oT+kMc1yHjMFFK/3U3fT9aMayWzny/cpZe85THucEMUQC5OOE",
	"zCfJuWgcTyK6QCE42N5dkTCKMCQCYHmKkmJK9JrAQIAxDC7kQ9U4t+8uuetpIVn8OI1jyBYdSVcUuUDk",
	"9WTrFYKRmC0Gw8EOmjIYotBDqpYmT8XV5nPUNnEmr23joUzFBtlyJehSMdumZIKnVTjJb/KNm+Bp9XrB",
	"VMz84FXdJBy8N0v2Oz16U9Pt9OhN+53Ips5H892KZ1AEHg5c/Qyw4uNRhBSThQkYq585+ieV16y63wjH",
	"WPh5ixhe4TiNDWsgr3yCWICIUAgwMbeJS3xJkxAKBAxVVXPKqbrRxcNsVEVMY0zktIPN9WzzmAg0RUzz",
	"qhxFKBCUtdGwN3CMomPbWHZMgwBxfjJjiM9oFLYN4K7rU91BHBvI1hyI/QxC89BJ+ESGQis4aQCOEUBX",
	"KEgl34tJw3nx2vm2iuPqGRWb3p3u67v1aSgPYVd3WC8T/qG8v1Cg6aJttCMaRTQVx7Z5+cJn4/iu+bbc",
	"80QiOjrGU8muHMmtc89lrW0KmCPeAmZ+nEjiDTieEhSCIO8LJozG6oC2tzyEIcFvEeNqxgroD3fNt8I5",
	"z/VvKAQaIvqBwjxflmEqJxJp9dZH4Bgx2RHwGU0jxYzPEZNbCeiU4OtsNG4fqggKuS2JJIzASMtGmpOP",
	"4QIwJMcFKXFGUE34COxRJrF2QjfBTIiEb66uTrEYXfzKR5jKI41TgsViVUoEDI9TQRlfDdEcRascT1cg",
	"C6R8EIiUoVWY4BW1WKLvXBz+F0OcpixA3EsyLzAJq7D8HZNQkTGgWxpRLwOZfWmPnh+fADuBBquGoHPo",
	"OTAlIDCZIKZbZieNSJhQTIT6I4iwpJo8HcdYcHtfJJxHYBsSQpVkpWldOAK7BGzDGEXbkKM7B6WEHl+R",
	"IPMDM0YChlDANpw8UDDaQwIqTDasZVOPWuwystqAZ0zezYbR3SuvYY5v5qo4mzQrX4puSL54Cdqh2Gh1",
	"Dy1ZrW3aE4u7JxbZ8+UXdhrPptPTV//efKq+gD3p+gKkS561JlzLkQp9/EvRCityF8/3HYNJgqTkR1MS",
	"AihlVrYSMCSBCraPj4YgpiGKUCgFrot0jBhBAnGAqQImTPDI4Tf4aL4+alxClbCgqwQzrXpBASUh9wmy",
	"qr9WoGY0Yw4jHGKxUNyPujH5xHKaCWUxFJrXfrwxqLLewwG6Egw2qX8zPKsccRl/SnphOTCAQl8uxK0g",
	"L8GrLQUWxoo5k3BOaJJG6qfxQv26dbgLuMIYCXvVXu5c0jUcx6mA4wh5tMD6Inm5yhMlyXD0y88riAQ0",
	"RCE4fL6X//v37eP/Wl+TyxmBPcvJzxCQL9Mo4zUxihRHD9370MSwaqpQOJLxQiAf4igWlu17FSK7JNSX",
	"TK2JZXdC99EEX5Gqf1IY4QlGodKXeRE0xR5id7q7cw/n5CyCw6lP3XWqfldQl9tQ1BepN+ECLYDu5ezf",
	"iKiY87TI/RceitYLLLfcrom6B8CUSKG9zYXLsRzpq1HZ5RcKJgmjcxithohgGK1OII5ShgDP9E/ZLh1r",
	"Aq+BO8CT3BDIqxTPaerHUTNkVZ4b5oADVMrgGcw7YZckr1p89nCN2TetZ5MnS11MG4HfCb0kIHAaMgS2",
	"FOhQOAQ7iGD5XwmhFxBHelHdOBU7plcp694GZwveO5ANVL/B/PhCJCCOuHpAKEEASpQT9riDlDHFgQh5",
	"ppZ3lZf6yCFpJd0T5OKEQcLVTCe4zsgl2wGBY6RnypYmsr4o1HyRXJe5hoICSKiYIVY4bckArcix/JwI",
	"l/SiuopXaQwJYAiG6jaZdgBrnJB8nYUOHNNUmBVny/MSNDpW6B6+RATpd9q/+5FlZUbTrKUmKkVoXEKu",
	"KJ98s0KQJnpa913/5Wfvu84Q5F5BBTwcM4wmj4BukbMOds4HvNNOOwqIdlQrENqROnbTxtISBgitTzUr",
	"GPquXAaA/PwbkaXdplGA0VBdSjoBJ0wKWi9gxNEQGF21q4qX3wfDgWqwtPK9tDozVulXO3TpZ1dvXoRm",
	"9T4aX4n81mFXknB2YymdVtjbf2qqp3YpSZ78qHSyeByh8h+WbhxCxlXT4wUJ1D/eSl5WttD6xV1yyOiU",
	"IS4P+FSKOMYMm6DANt1LI4GTCB1cEsS4WskcB2gHSekGcyk7yE7dgP2cMBpFMSLCvJnODmvf1S5tMvDU",
	"tsjgdoQSyrGgbOEFmoRV7YcKZN2PGZRfRAgJCz/1hw/eGo4O1PUPLuz1L11PQF/CCZ6WzZ/djAkvsfB0",
	"b/Mo+D3jzY9RwJC4gTvCDWZ9JUTi66ZgkKT2VPYokQdd9UQpvqaxbtbu6JRrHigwndoZS3d0rw282S2p",
	"uhO9S0bJ86tE3iU/G8IoAShrAPRrph4iOXaYRkqngmPER+dEbtK0wBz8/RMw//t7E6yAPUykbLkJ/v7p",
	"bxAbeW1t5cnTEVgBr2jKKp82HstPO3AhgbZHiZgVW6yvPF6XLbyf1jeczu8QuiiP/svonBynSUKZFALk",
	"QUJB5SJWZMPNTKSUvLHWIz1Eo+loqIbBBMzkkrPx0ByxhfrtkZz375W/N8ERJNO819rKr38rwK1vgK09",
	"efa/gq093Xr49yZQmjTbeH24vmFac6F41PUNMQOxgqHus/r3JjgWKMmXtWr76MWUexxrb5riXn7NQSJf",
	"zV+dLufkuXb7k5ADayu/Dtd/Wdl4bI7Uy2hsp1zQWBOWXTKhTcqKMq+jdDlaIRuCQA0EDIKZA/BOWRZG",
	"nUEw0ZdRiXGKLSza4Csshl54dXH696IxK5ktOA5g5IzXq6B7e1Vvr1rNGZDusofpcwNL1IdaPK64yVV9",
	"uPwapJKw6bqxNfurKUkmXPhff+vFMbESvbxmlzMczJRmQvUEndzi5DTKi9RDR/ezWWwbYOXcTHz0j+4I",
	"pN3OzO/Q+WlY7xmXS2imSeZ0ppCstK6bOcqVhdcazUzm/yXPywFotvlO96ro/+R71bhuYO/PTLlilbwD",
	"Pe5hxWuKzVPaeE3d104rQyzlUyoC1xvxVtQFzc5xVVeTFqhqPrwOkNuOdiuX8TW8al3JGCIhYiisfYaP",
	"TAP78NaO26bzLc7TuElOo1oOw3x2GQ2jylA/B5QQFBipPztsn4uSYtZ3d/yEyHwGuzuuQqk0g/9i6J57",
	"ztNRuu8Zr5fNYgm1JW1y3cY48Fsh7CCARL2WXOtylesUjPC1VjpmQSKIxZjAaJitWTtvyW5DgERQd1ww",
	"PCDRYrApWIpKV7O0q6EDwPqjdOXmKiDsYIbvhPZKhUVpO9NWV85QQDZFotuz6S7lRPXzq+L0kN225IxT",
	"JeOZqUcjC5czVLYWIzGjYRGlXAXVKUFKjaOUUYGgbHGEeGF9TSqgphU7Izc1K86aQWFXvoMMi1qibohd",
	"iRZh2626488k5rnoogh5PtGtkHHvps0Wb0bJG8Zq0dk2wDAL84CcFxWYeVzEKeFWnl/qFpUWnE3h/ZrN",
	"6/2aL6bms7PCDGBv8AQFiyBCryi9sHCyG36GJpS5+r2tiUDM+Vs3OEJjSt0W+Q/LgKKwlMrUnjbl1dQO",
	"4y6wbhxnzVXg3Ig1iGzvW8XD8uBm7s/GwtJeb4Z+vkHq8M4NvfRBLKfV9lpr1btBgKLmuPjLkjhYWnUZ",
	"j0qfC6vwfPctraVZCSN9Din5t6Jfov6d9yqgL+6F6JxEJ+nRKPx6B8OvzcFwODCCc7cTtEzG7Xkm6nEP",
	"uN8R0f0K9KexQWDNZYOD40y4qmUEY6+rw0lhEB3tplVQrFsYkx63cVM3eUoPjjtv4W1RnLbb8GO0/LKD",
	"p7UugKH6Vh5LGzAAn8GNJ79swrXRaPSoK2iKk9YDKrPKLgWujIC1CQJBkna73cV1WC1biPnF5/SPUUy7",
	"4pdvhLKrU5IOskHN6rqCttlkygs2Uw1sTeOrQZTvIDMP/jbDAgcwunE4pW+hbrRm9Ws+ue+rsyDfZ7tI",
	"3zfXQcTRrteQpRJRgg0WqlyD1y2MOTFm8hsFMpdM85UnN6gJF7UL0d9vsAavZ4Bvek4jn9r6xAkZhIHA",
	"81xhZjRFy3IcVg/o9cwusq5La4CUa1vHdZj3TVsUNNXycKpyaQUcNL4I5kSMk3t3GJS8EXxQ0LlqwhoF",
	"pv6ovHVtAKzjR1HyyoAimB1CIRld3hS0qRqCxLQsbKai1NeWdLsOyTupJ3qo03pQpv4rpUWeTib4agh0",
	"xOMMRdEKF4sIgWlEx3YytX41O5xCTLiwzpzRAkQUhkhPodYUw6s3iEzFbLC58eSX4cAMMdgc/N9/wZXr",
	"rZWztZWnm+fnK/8zOj8/P//pw0//2/fqtqcS0JzkIY1w0PGROHV66Gv1qZb+1z2p7ldXDe6Xw7mTxcAQ",
	"OWD6Sp5aMIgjbfEKRAqj3Df2c2miYYlc0pirAJagA1UTpQcXYNXQsvToJUNVd+/q7AwUHLUp0RqtJBy9",
	"rscueD/Xo9p9FzoR1tyKJLlLq3+7kRpUjhBBLo4RIl08o8210I7AiNjIAkOnurtBZzqYG6mNlnwAsj6F",
	"J2BZnnBpka1yITU1tV5DHQbI22fkKlyGUoU17gYOZhRWVcTEgR8xXTC61y+7xups8vXmUHOumnsD6nno",
	"m9uenbs6gyy8hAwp1Y92gsNkap42UFDG3L5N2qzBBgzcnjnjFuzRS+V78dsqDpRfqj+1i6sOP6SXiKHw",
	"YDK5oZBSWKsza+WbsxDP16IIUvhU1d4XPhd24PnuEWAK2N7NR/AgsbZlfTudgEV0lVCex3LBKSJidE6e",
	"w2CmwtACyhjiCSWhDkzJWVd9TY0aNIAJHOMIi8XonLR7G+pNFG55QKNIZ8/L1Hi1rIZcZK1+WL4uW1OV",
	"qU838We9cTRzNWM4LeRrrt1dDZwqvpD5yPK8fR4EzygVYHdnmaG0M2cXyl7xH5VPmSVKGtr+XR5klOvY",
	"Uq6OyysrDF2AZlCormJYPL56OlLhilvM6YlqqZSHMSRwqmObFJ3Ub4bK0BhEaSi/XM4Qsb9b7f8YgZBe",
	"EiM5SLpuQuSqV9C2O9a+3K38ht5M1jp7d2/a/1ML2MIbaSr1mm7f8l4Y/jafq8Jmb/ZcVYdYwuaXAywz",
	"+CUndAequMyDVBxMzL8dQ+9N3qnCIp0pPF/dWb2dSxbn4tfKc+MKTi1sks2qZf2VIoQEYEikjKBQI9wE",
	"iWAm0S9LUanCcxqlyfwm1z12HSIFQzSBaSQGm/9W3qItMGYIXkiMbtzJeAHO3XWdD6rW6/xy8TKP+RUs",
	"3qypeeGCChjV6JTlJ8cd1zdTx8hNQ/2+JugYwaIJOmW/MAWqoeeyls+/tGEvNcL8ojVuaulQpeFXFmvl",
	"fcCNIki93HoA9XZjfqGzICyTyjvETKXNW2S5vK3OVQ5fHLN5Lw1Jp3cwZ6ma9VkaGm/Dkjqu1KKYRQ/N",
	"UWSyXdJLFMplmdaaTDIdrgiwuqeJiVmsgmHKaJo8W9Sr2yI4RpHk4xXzniCmnEhVN5W53Bpa8/nHarkF",
	"/ZOjKX3419bKGVy5Xlt5+uGvlezf/7M6+vDTo/84HzvoTpVK9pTAOcSRZCBqUjnqnIoO1bFnBLKeGVLb",
	"vNsafErr25CSUX3dapm+lElyAlJSnTc7x6Xm9/JwqRtQbwjbYE1SkPrFZdly7DqyeAXt8ywoCEyiY52L",
	"POuQM742C0kIoArSopJDmxvPQiSxx4w9XgCoFXcpwWIE8kjA7EeVMWIT/M11UB3X+X6G4O9Y/6Dj5OQP",
	"M/2DighU19u5av/Z/Gt95emH8/Pwp0f/OT8P/+LxzH+vnpOASqa+i9MtMm01nVM+04owQAFLnkIuV5dE",
	"EEuxVmfV6Rxsrac6NJ3t38/MIJ+GTjx2nvK1nLvetlgx2tA2zjgf89h0KFM2z5i+F6kSLF6FbaVJQ95K",
	"k3tF3ka9gEZjQu//1YcA/oAhgBWEWi4asNr9dlNU1uSP8AkMtU3zvDx+jUFGKBx7GMhJVn3kB7R5Khoy",
	"QF3OkJgh5iY8AjPIwRghAuwAzpmPKY0QJNqeNUbR5xQR2bLpvfRISp2aJNEiT9teE19dOTyzz6VOyJG1",
	"OokT9Udd5eNbJm07ccca/blnv1XjC6d4EyhM2Kh7+peQFw6+m6HR9nhWF7NaDH2VbTuIT86oQ3dLHilk",
	"uOQR3MAlwAP47IBG3rvm9/72Nis6glea9CzBF3cJ955JJ6eEKuPY+4l/r4lo/QxLOw1QvpZYO1lmDTX1",
	"qbR9wK1ft3KU8TgEc+Ynw760p24GR65TVLnviucRL/pddc/GcBc8g82eZwQ3XXfOYSMwz5xpZogAeZMd",
	"Mo65j8mp4TMkVLsdeY2tqabhcm9Rp6chZ0JvxNI4zl1tOTvdG1VN3DlaOh1nNfkk+gzKe2sJNqtKhIbT",
	"NU2a2LwZvTRqKEkIFe6ZQm4vIjydCbAtCSON3MvqeH9VK91I4hhkqrKl9CFbqSox6KpBUrxi3wL/sZ8e",
	"vbGnc7qbY6EyZYOUa1fahNm35I8jIK+I4gEiTC50cik1n33BGsz+N1X01Ol7SvDKJ6iFQacroeDYfi1s",
	"0aI8la55aYvLKlwaXejkBldDD73ioOSKP+HCtmroZCvcgQLmy3TRXOkGFc8A7dLl+Lrup1zpyZtjP+Lr",
	"xVygReMifkeLpSa/QIu2ucvIXgOV6hI7HXx3ktCBMtjMGRIt6A0P3dmXvFSUYVEL8rztlm1aD32XV8hG",
	"BoVM+HUIjDwsieZH5SusiEcYMsQzH4zWjYOHlrWcUS6khLmZUCY6RG81AChbrPfk56bea4n+2iJWzXKv",
	"yiGu9P96+ZpqMjydqtQxigGXE2ibhGb0bRndhKEJvtLmBoSVykYOtwkeKnuB8jyRP/BHzgzmK0wFjVWC",
	"chvn8MjvAtZLlLcsUZpU0q0Plxxxx7RVvuZzGs1RqNWl3ZSqWdHDXpa8dVmyJpX4lsa7lczjqyS5FTl3",
	"DcfEpP2+RTV6fdJvPqNMDEEMgxkmKF+nOX5Ff4oxx6X04JocOXY/61OxrYsgOAmHt02ZAyetsf5wmvmn",
	"F3+pNNxBuvJs6Rd3zGqMWs3PpR7bh6eVoMntw9NymOX24em+fI3zRnsqCrXSV/9c7q5/LY2wg/lFpb/8",
	"sdxb/lbq69agLnhUOx8qjtjOt3KQ6Q7mhrtwYeP7RSAiKm515veqQ13WwbjSffCxAOpEO1HCY93UyRrf",
	"XOrdPJoHOjm7huEQGPi6tzcDr4X9h3YFdLMaqEioPfnnh1neer2poWEWarmLnfzJKPGSc2WfNh5CtkrB",
	"UCJzqmhbaOoFUKIhklU47ZZuu4Sv2XNUu9Ia5bb9VFJoz9Wr0Wuxv7gWOzuIbqprxfH26urvVl3tEFwv",
	"oc1WodkFhWY8oURVI6gyCiVB1HZuF46WnKdFvsvm9e35BY7sk1W3Z/VR61sn2JfzK2jqr7yjgEBXAjw8",
	"PXmx8qsSykoVyJxJlOMtjmq1pbKddZZqV4I5vl9elzq5/frEm/JrlmqzxsPSv2u5gwdcO1MOHf85I64q",
	"NzqbfoakMWI4ALs7I7Cj3foU4T0fMErF+cCPJTREjVMniBn+T1XvG4H3NFXEQy9Gx+/EEtUnMMYRhgzQ",
	"QMDIql4jBJUr3DVi1Oa1X/vl55/V8UFtmwlwbDrodJy+Pj9vrD2S1EukOFzlSEzlfwQOLhZgbLwBQZa+",
	"bwR2J0BSpwxiQx2+U9yMQgG5Tw5CB2Byef7UyylHrBFa9FKVj7v1g6q7cweJUxzJsmRBJkgwFJuiKjai",
	"tZtXYWHoXC4p/HyUjV342YomH8wKl/Mvd8lIW9mMAs61Nd4acxqlAh1CpZf/t+qFnVGFGn9sFUTiwW0T",
	"geJ4JBprWtgnnusdD3vHQxdjJa4s52you9yug6Ea0y9pZZ+Kkpb6ucfkLy9p5QfRSdLSNLuXtL5XScut",
	"u1bnIFJts5xviAkxzcNtSkKLdq54BkUwq6uSLIKZDe7Jc0eNkQ3jQSEwQ3eJ3smJqH+rDU5Paiutjk5m",
	"q92SSx0VGiuzZISs6a7xMsAxio5tY7lRFCdRrUuM/VrK21mNCy1FIt5LHZ1yOLj/4SkHdtr91l7sxht9",
	"46vcOQmXaj0ESAkzMIoWAOfhuA5qzOAcKWFLWbcDW8dZ5UdABduyKvR9OasT/pdzYMpO/PNzWIWVKPRl",
	"ktoOLcZ0eo2K1GpJjylVDBcHRyihmVzl9fmbqDqq5aoVHerF2qFtHtKU1cRpP0yoqp4peYmYCvRIJfXQ",
	"NTe7ZcKVQ5s23r16S1VW/ASmWBzJ7fjWyKz9Vnt9vMSimBTRVBT3kA2aEnGYxf/aEMnVSoSkbGNJkL5F",
	"D7j2m8my4BTCASyEHnAdOpzHRqopCx6T+QNbH4ls449NmZgJntrV5BVQa2pU2c/tasR8qEIB/mrorXpW",
	"jtAc1yfNYearXHTKUc4NNa63UtInW3xl1mFdTPWwpp5YVWlaSGTavhpTrMpcRN/EqoRCYNU0dRVK8aQx",
	"159S4cYpV4xgjIQnAHeMALpCQSqWKJcu19ZIHAWOkSFu31h0MHjAHxSDgx/ED4rBwVIeejB78PkBwp98",
	"iQi6GQnz23GUksGnD0rbVPzRE7E7fwvZ5zh9PydzzChR7/McMqycGC7QYqVQ9gmTjzpflo06T4mEsTep",
	"B0tJrbkjloAu3lA3URIkCwDZNI0VI5NyleROQBJCFurErIAviIBX8vJIGQqjKLTqXg5iUzzZzsRBghNV",
	"qGqqIvGG8kZhhd4LcIlYvgiQkhAxAMEY8hlYCbQF4crvpH9J2cUOrlEAy486o4TNDZGXvjIJF1JCrARp",
	"FtqB1KWklqTkaLu5zF3LusnH6yBpr8Ps9nHKEX9qXVdT7eKtQuXinLghef9UBicKBEuRPLq8nrqX5pmU",
	"EzWPp2/LFXyiNfaXzLfoIX8E5PzKWACFsj2hiF5qs4J6heUWOBSYG6OI+jVbenedRUGt7yHI9dwANEru",
	"jC3QljagkpJk1zIDtWLcgxkkU01zPwPMvrQmQwlV7x3JCnu3MrCV19Bh3uQiX52cHOpcX5ISeKQKOAqY",
	"5+3S6RGAtRsySgXY3qphvji/pCysY8D0V2CcQmfa7lVdVxbymY3nc+i5wIlWG71FLEta4/HxvcCJ4bsN",
	"DwvmTgd/bLGIeCdgnLw51r7n1lrZaely9Au06D76BVp0H5xe1OX4VZ9uB/opR6yeR7RfW+fqYLqrKW1f",
	"IUszIZKO0g3RK+km30iqcOglI60CjaCOQGPt7VkCNpPPUS2FI3kvc/7ukmEhEPlscYRVxRErTUCtY+cL",
	"EoAGQUXnffdtnmW+A6dHbzSpDGgsSf5EmIj+MeTq6wjsClUWU7MxCPyTIpURisEYCaWsT4MZgHwTnA9W",
	"JUVcFXTVKn3/o1r/plrXWXxrRZ7s+O5fyrE3so6u31A1MSs8CY3cSN7ScWa8FZWGurXq3CkIYBTJdzOI",
	"KNFSqvcmzWGEQ52UreZOyfH0fdOsICWRzh9qu0r2NwgQz0w3+VGPwClXFgQVtCEvuL2ZmgFWcpJ6u8yq",
	"Lb85XtgDttVu5FlIplqtBHHDR6tIiBmKEk3LhA6RMDvKMlMLkWTGiqXUOkP3XH03ZjeGU1RXhKSz00Cl",
	"ynSpmMi/3eoiHbn01FI3VQncFDXyVOgGCQwuOmV6q6v7VAuWwzSKch18roTanexTcaiVvhV9lE3CXHQs",
	"eeD2eTAC76Q4wpFQ37aiS7jgD7SDjN4o5iBJlV1CkvCFEqtLvfbll0InxVLCSFdKR1fKYEdqcm/rOQfD",
	"8mbUqB19VCR8snHkH6Wx5E9mPAtSz+3YrL0cTTfOGc06Vncu81Xt66mz4cYPmCdOG4QPtndXlCYFQyIM",
	"5CU/wgSewMDDASeFa9S6KefWqR3ZAJhmbGlfmNb9MzTFXEjCpshPDBeSZMEKpsmOhOokOsYp/WB7NxtM",
	"yfMRlZSTA6PUpSzOKKhsqwfibvLHLq+s3a/35FTu9vsnVzplfENxHJcgGZbsJiWgcser5rBus6COtEw1",
	"7sLstu9TS9/ydVYuaVX60lnAriszdbfMUy3ghoPf0zFiBAnEj1HAkGgG1W0tczjgarauFpR8lUB3bDWd",
	"3NxYoifoaCHpBpB8zd4BeAKDhlHU59ah/CefDz90INRqIza980PyXR1lSfe7M+WoE2IuMAmEyfExBJcz",
	"pQeFwQxgVSaBAy0kC60MOh9coMVvShl8PtD1FtAVjJMI6eyOmfb4t4TRMA1M1L+k8JT8lvIVBLlYWZcA",
	"woj9NobBBSLK/zRD0tbcrUUfAd/uVOpZ63JgfLbUb1oYo3Ol3DUOmbnnEdB3m6dRXlzsjU5+oj2kRDDL",
	"lZfamLC1v4PCEXgeJ2KxStIoKs3OTZUw+W6ZGClPrTNn1DY6tVdur7LZZiv9rIQvMUzkxv+9QIuhOuNP",
	"WuPvT9hSvXLWk8frqCW/ODGQ1gfDaEgXRMyQwIFTijPTRro2AXlz9XHMIcM05Zkrg1oGH4Etp+YdXGh1",
	"phKvqI5a+zf36hgCu7BP/rgDTFIP6u9pBkXeH+zEm8u/IYhwjDMeN8/dq653phHRJiac5QYs5NZBTOUF",
	"VN7zCkJZ1l83XF2FuMJ/UpR571kxT1CAOVcfNLNkM6gZPsjxMIPaC0P5ZmCuyYKgcpkMo7kWLAm6EhZX",
	"8vzDGbi3NZh0Zv2AEo65Uv6oseSyjJOacQxAFmRmp0XNlNy3VT2rlNxMxe5LJnGCLq2BTp9pokr+Z0ir",
	"Tty6VmpBuFgAQNuP1D7t0ZYi/3Goc4JEFlIG0saXCDOVZFaFyqAhSEkkxfMFTfV6GAoQzkBpFJAqewYB",
	"iDG5HR2pWKPqiiEmmEx3BYq35VtQ8+RkN4qnYy4PVvLV6nKZdSrA6wdTEigJfqOLCnUTe9B2KyosIutp",
	"L4tlvkND0FRMhLKvWcqmxLzyPc/2YRfFQaorO6h7qgEph7FAj9BEgJQo5CEhoDEWjmWRI4ZhhK81p15Y",
	"qDpHbTwGD01AxRgFMOVIcv+Ya++jWUqUBY7mXxUITCYMVSRENXqU74chAzp9A8t70hvJDI432ol1A6VR",
	"qDSIkID5+mj9CQipDlGREnU2h77lWDLiqrIkd9Se5Xsjd/YT4gLHSo30k8Y2fG38t0yxI7UInQQm8x+W",
	"8zKkKGXd2FqbpKgByyy3RsJsLZjgezNKz1mVqfVaD3QZP5Ng3qWe5snXxXOUn6wP2bT9ri6RSGbdy9Ok",
	"KgKiXtlSnPOu5G72qVD/fX4lH6fBcLBDEd+nQv3tDdHWTtXNVWt1m6zOaEGQaa8N6vKLEoTOpj9Uwd6h",
	"yGpulu3uaF0+XJ33fld3Xa9ydjqsv7UUxVdVVmLpuhgS/I5jabViWvZNYnKRTYJRBBL5xnFJWbyskqb8",
	"huKr+gD2rdZZa3RbLSp7QhcIoSKvpHpDTjJvrEhFtaRmhQwEJqfFCY4RFzBOGnLp6qKmyrH+UvILOhCt",
	"ewLd0OS6WHYuQ+ZDnTyj+3xTRBCrMdluAf2GB9kbWggrgJmqCuSj5PVkuCpGoR22wSFN0gg65dO0+DwC",
	"RwiGK5ID7lgg57MzR+5pMcJES6gSIJph1wRNmc8gcflVyqaQyCdKtpMs8ZQy+edDHtBE/6pp+6OM8Rzc",
	"2Mhlome8D8MlQV6R0gnrgALQS+V5pyOn1e9SRJHCMSbhqpzrfGDk5hpmr8Cuet1gDHPvJpDR/GlWT0Jz",
	"0A+4E85j2N9ClFA323M5tZEXBgWtj+v0WXqy+zCa2wuj6Xans7MJG4+9wBXoiBo1vk+BdCgfb6f8Rvbi",
	"L2HAbXWgcmoDuWwVDHWcchJp5ZiOWPayUn6/py3w+vhgHxxShRvK86nOUpvWgFdfT3nVQyWMmtWMKoCk",
	"SZN7cZnHOUQsQER4bY35NyueGFTRtKSIK0neWLfybvAIRVDgeY1fx1GxZIpuqpWvFmRdql9tefpaIcK+",
	"QvtUGOoJibEEqp3J9vZppXPEHH+QTLM44CxYxSREV6OPvBs9K5j3ffvOvlpQu3mOWMHt3N7KKRbGeO29",
	"iUcN3ioFZ3kH5i+xcD1XlIVLexy4pvU+vLQPFO8DxVdzJFouWtzpd7sh4/nAfkNL8XsxeDz7hvtkEF9B",
	"CDkrHUcn/YZD8fto8u81mrxEdRqQXMVY5xYuWDJuFJmKbpEZ5dDO1qgM19myrfExn+VtW7ZeE3RcbrFc",
	"5HERIp8Z+Vsc7H5rFlhF31aEmDgyRdVLZdvdHdwkvy2UY/tzH6d16iVb0zPjcXGsuWzHowLOEZNChKpN",
	"q8yKY2MTHKOJRHo1sZQvwAt1npvNQXjt4XVNoXXn5+H/qS+3mTQITyc6k5eViejE7MjN/c29kNSaN+33",
	"MkcMi/b8Bu55H5tO/iLwdkTnmAr7KCrPWi9XYTJPlnf9tXJnrAiTp8J1MuXukgnt6F5Zu5Z84Nomzoy1",
	"bfRSnE3/7n1Ej7J3UT4bAF0llEtGA0O17a3DXXfTTuL9Y111x6o1fJVGbardgU3uVZDs8pUdL0gwGA5O",
	"TMIG+7j4JcOCHUDtB8v9xJhYO1QMk8QkHdw+PK2lWEnqMyroGt61qQlq6ntbg0ut+abWHPMpo9aLfaWf",
	"KthJPnV93Wp20/ZuNa2rJUlDDSTk61dr9akeoJ8RaCwp3qQvhfbV8Jnh5HOkC3Yrvly2GoED68+if02U",
	"94lBfZwVhV6Cjy0/Xx52lsM4iTCZ7krO31t3M3ttxkhcIkSy+ueqq1z3PTwgWWB2Q0x23VEP3aPw7LiJ",
	"OityUEuo5NdygWJHm65ck4y/i3ZnNY7RmWZIUB2/pLxzDPFT0p/mSnoJstcS9VqiAjGTKLesnsjpedua",
	"onxoqyvq8fULa3xM5wUJln4pFbXvdT7fr86nREMaH/aS3sfmGH/IH2XPtimj1qTwaEnnlGVIL+ZtwKQS",
	"Hbqr6ijbFjoYL++Qo72AmGjPaB9HoWM/CZVXx/bGEqefw2Bm4jOKQ2mfFDuAXLDL1jTj6v1GendJSWW9",
	"a7LUVFVI31VGKs871Hz/bqB6c/t/pvIN3oyUNqaXsjqobRrHWNQ5gCo3ZdkAzCA3uVYuIVfnXxMSZAd+",
	"2eCUlQ3u+Fx5xu7i73oDHWKpKkw1ygtdHvjdlBSioEudbh48xFkI4DhCqg4dSSPlvT/YFCxFPv2avO00",
	"5Q0T2CafMYt5bV5gFIUND7TyfDb+Yio9k+mXY2KO4tmNszof7cmVObNVWLOOrrPFpXqPTWduNIk/kfGt",
	"boreNQVptUNbljpTyrNOOtkm/ZDKKnts/Abr0KvYqKqw4YJBgaaL7tqa0ogNwHAD1AtEy/1sddJm0yDR",
	"v5bzeJa16Cp+XePISZ6DrlHpk+ZZk8LqMXXIY1s+3E/qfFiq9vUsDaeofRHl9irhiMrwcDJjiM9oFLaN",
	"4bgO+X1ebBJRc7Je/LXnLgEdzCgOdAYDU7mb2z1KJCuejKtRLV4FH1Yd89ktJXM6Pn7VlMspYXgOBfod",
	"LQ4h58mMQY7qkzLp71q9xGeHWd+vIxdTYUmtOZPMzhWAuqdN8l0c1xC4nIMfd4+5xdZ4R/lZ5PZLblQ2",
	"W0tTlpam/CT5rnxEro4lM2wY1to9kTJi5Dx52wIY2Rr6ISUPbHIkoCP0HKfmXitwt1qBwFva6DidTpEK",
	"qlDOd+ZwAlsNSMFPs89DsAbwxMZolfnAxxtel/peLfBNVomtr/daKfRamupytihNIA/aMK7ngxcQRylD",
	"5wOzHhPZiHke3IviRCxMMKKKZSwKdXlI8BY40qVkgwgyHR1gfUjNZtU1HqeS8iAdFUnniDEcIoD9HgW8",
	"mcTZQIoMeKYi6CY4HxxrpuZ8ICV/Z6d3fm0kg78CSbhiQDq4ScVRs3FDJjxVRn0PQtkEXH2mig2KhiA3",
	"aCMraNC/BL09p7fnqB4l5FnOpFPufLtWndLofidgT6OiJ3CpQc8FfnnbkO9IOik1y09BbyL6Xk1EPrLU",
	"hvsVB+HC229UMPUswMRfa/LEqsvA5YxypyiSwfeJ8nuk7QyRHr/LZjPa2y23nVsVqZLIbmlH3yUTuzXa",
	"Gcyt3hINMeCF/GMZcC8h10YCixgd48GXMQp8GLbcpxsYfrINmLs3UueLY3RGbZo9m1P0DdXemqU1SJhc",
	"U4LyeGTGjQOXmm13a3/LRixuHT3fWn1zsL11snuwb9OLyR+LPLBOyKNqNDNAAwSJfkNsz6wKiCoBApnA",
	"QRpBBjiWJ4HFDBsLDWQIDpXIboIHwZaqqgtX99Hl/7yn7GIInqfy/q0eQoatK11KYDzG05SmHDxeCWaQ",
	"wUBldrZ7LVUSBg/PBy/3Ts4HQ3A+OD3ZPh888pInrac+DmYoNE7hZaNA/mJz08pmEqfyGAMQ0ksSUWgK",
	"YoTmunE3J5bAsf1KTaZXYOqzeHiJVlX1NisWdFC8FhMvGQzQjuNq3lXnLpzL1fh22nYVGu0nSg5LVNzi",
	"vI5XeomFS3L9SSlqENUO+uGT/CLxzCYJg4ECKYohjgabA4Fg/H9NIjydiUBEI0xtkLUmKS/UF5U2i9EI",
	"nCAYD4x2c2Bf0ELvSnqFv4pDfHjo6/bIMBOmxppW8QcRZDpM1ynDRif69VD0AYXTvIieSdiEmSpjIi8h",
	"1yn/IhwgotXsZmdbCQxmCGyM1iqbuby8HEH1eUTZdNX05atvdref7x8/X9kYrY1mIo70VREq3rcEpK3D",
	"3cEwP9bBfB1GyQyum1w+BCZ4sDl4PFobrRu7uroHkqFYna+vwlTMVoNMTT31PaIvkVDp+3UGMJszNTdF",
	"jLIMOpiS3VBuORVWS6wyOqhcWmrejbW1UuF6JxXr6kejUtLXvjURaz6LunilXDG/SxD8vP7rrc2XSUjV",
	"9ICp8gfJi6WhUFsT4FSFBhShJ/FkWDwBk0Mc1Z7BW9NASiSls1Dp1PxnYHupk7dZ9hVL4imF4hlVijJ2",
	"aYqpkI1nCIbKfmzvdypmlJnsXVIkzIBZphof7vAy1B/OidqJ2oa6Efcy6TMYAhs1oSZdv7edYpLv9cvd",
	"/uHgyb0AeteI11qse84YZZ1RL8iDX7gOfrECXi0eKim4Nmim6MlVxEfZs7Yjb8NQlfXG8C9ZQ4meOm2r",
	"dSNT+eszUdYUM3EyY5qXXY0gB1AJr3QSM1Fu9MCmgnxgkvkZFX3m5VLMlGjJg1pQTh2yVKFNhGHoy/1k",
	"8tVpr37BcCDyBIfKR9VksLQpvHRqJ8xMwt5iQn+Vlj9LM+tbaFRInXt/q9WuPEPLQKt8jCYdnQTxBQIP",
	"fnswBA9+k/+vqu/9r98egIdoNB0Ndc7hdZ10eH14gRYb/0v/sWHYbt9O1Yw326lbwdBNbKkvXrZJN91m",
	"nkrzJE9tqrKa6DyO9Ret0B3gSfGWqzQpetBSzlJVpneGSKVEYo44KoTEyRKqIFR7M3CsspvkcGo1a97p",
	"U1dLRZSStZ4V+n4fvlMCDROCzBv/+B5mfUHZGIchIvq1u48pj7XMckoyI2fhsat90FSkXkJ9OvhtXRkA",
	"dnjVqo+a7twURGoW8IyGi7tHAA2yXDQVLEWfKpi4fl8L8QE67FHxrlHx57Wn94GK6ouUPyOslS5fPQno",
	"xPqu/iufvU+aUERIeFRz+vciyQAGAUCO+kVSsaM6NZGKVhHVjXRop1aSF9MrzR52U2XTvOumVkSRXHx9",
	"8qt9vX8Y7P35Hqbcp+IFTUn4jTzdXlmUIaizxudMbtCAXkV0fInEPePiVLsEfj4iDgcpwf+kyCTLVo/8",
	"l2G4e3Tt0dXLaUMR+Ms5BbMbctqq7z1jbJIl17+tx7OrLLCipv4/yx1mIStvJ0ngC5OIXgj4nujS/Ygd",
	"35TAMRwkqZdxUemiS7zLdmfe5Uj3v2dqqL0Lvgg5vDfVyBcliL1mpifKPVH+qrRAqzBJGDUZzby0fEs1",
	"0Jk3EFk0cbdVplb7gNV22LKT3xo911Wr3AX39LxncHta+hXR0m9br278A5v9R7TPd5uzyI4ZqvcM6T1D",
	"es+Q78YzxHNHTJoLMIngVJUo1hUKdQIyuZo4hmxRjPHgI/BO7kSBigLFntjUPxosCpKFXGYK881gTjSE",
	"cfRXAFe5gR7o21S49w9yGJUd/lUF0AdmYDnUA5W/hqW1qO+09d2yLO3HnWr1NX3tfWbulYXZp8KmYP5q",
	"nnaNUF1cZEoPd50/TJYk/S4kAjP4PXu6uLP2ypPereWL4WiV1+7gsLJjHVZaEVi3zBB4KbVDafDe/6SX",
	"q78dg7bzCNYHgbXjz0skbg15bs1h5D74yB5zesxp8/toxR7V8Nbwp3ffuEUc7jnbXpX9vfHSNe4Z2irX",
	"hV4ZR4xbo1jfhIvFMgL4/VGoXtjvSWJPEu9OvbAaIlVPgWd5VXykM0tUkyvqtRrA6VtVOeQfb1HxkA/6",
	"TdBTFwo999eTuh9HbKwnOQyRECkMaMjMo21+uqGT/62iljkybW5TPeOb3BpW81qft0V/hrXFaC4IvSTZ",
	"Qt7a7G1+46NqfFRsO/halUcbGjnKdxnYyXtC0fNEX45A5YmGG8mTm2Oxuwb52OYb7/XIvR651yNneuSl",
	"McrRKt8aTvW65V666InJt0FMGnS8S9OSgsb31qhJr/ftqUdPPb5u3QQijEZRjIjokC44b1xwNPYx+8+z",
	"plnG4M7kBHYM3dWhECp5OAGY87SYKkWVmEoYneMQhUM397Vxop6h4ALgtuAy42vN/ZMon2rlv445CCBH",
	"mZs3tnoU4yNfhoiqKwGjyBTEk32HplRFBmV3Iu0qr1Y+RrpYVm0MBmdfTPVROfiexn3fNA58XUQuxx5v",
	"JFflc0tQV36dOyYDrnToQ736UK8+1KtPArzk69kn/+2T/9a9Z20RTaTh2aqLbqr0uKNAp+o89xzzVLOA",
	"3iOqD3/66nnVJYKilqMBupePBiylBKyfsg+b6qXIb0dT5n906yOolkO2gnrsTjDtG7GNd3qKe4z7cTGu",
	"OfJqOaxTne4Y73r7+d3gfs+B9/5333z2xhoS1xSrtRyFM1b8O6Zx34RV/4Zahi9C3nrlRk9ae9fmL6hO",
	"uUE6XA9h9tTq1b3ugB5/cwlvK1vIkgB/abpsF9Ku8ukpZS/1fi0Ua/kQjc9XUd3ML7RXVPUo+4Mrqj4L",
	"E/1qq7vAxV551SuveiLUK69uSXn1WVSvTpV1F3SvV2j1LFDPAt2i1DKX09TKJkdIMIzmiAOYudDqLqNz",
	"4nep1gO2uVH/MJ66x5QJQFmImAp+MeUBlOes3BCOERcwTope0g/kGA/AQ4IuJQGcYMZF7eLU4IVFhXoo",
	"VSacB4PhAJE0lpcBqr/Ujx+GN/Uy1uevz00ekXUTbvNAv51KDd+1//2disXy2HoP5R++1IJC3+IjMIkQ",
	"aouteSHbtMXTvNAD9TE0fQxNH0Pz/ZZL2jVRs3V1keymFV2pWwkMTR40fqwH+XJliBTZ6p/GHzx4R93W",
	"LiWIik9hXYyOanVHcTl67HuOxXEm7V1U+vibL4WeFb519V/130+rAsVJBIVkjzimpJ6hVY+xbQ2y5j6O",
	"9sS0eps3atVmqgJ+9kmsTFOju5w45OKGuTh7vrrnq3u+uo9Nl2S2RLd65rZnbpd8PTuEr4a2pl/5kasJ",
	"WS1dys9+S+/uKS0bJTvO3MfF9pa/r1Ce9TLBDMFQc4DZ89eKxi+RQIvXs/HLAB/g17un16dXe3iX75Kj",
	"J8H27vQAb+HjKDzdxZcYbkQXu3jrl93t1/H+9f5s7+MfVwfHa08Odi4Wb07+uD6Ln4v3H2fx2fF6dHDy",
	"fmPv3d71wclRvHf9Hk/+eL54HaFXW/jg4/PH+ydb13sfL673T57z3Tiahdu7v+ydBOt7O3uLvY/P1/eO",
	"LzEkR8nuR4r3r/cen707vd5/eSr2d17jg+21tYOT9+tvTqZyBrF3/Xxx8PLFxd7G2+js3eljtdI/969l",
	"X/jqaC14tffLm8XTWfjnEX0Tn3H4LqThy/218fb6dfjyRXr28gUfbzyJ3rx7+3O4/WQWvHp2/Ybsr71/",
	"FybjOEjP3u3Pz949IW/euX2fXJz9efZx/Ortdfjy7eJN/PTy7N2Ta/gyisPtJx/HG2vzIH47G79cv36z",
	"4fbb5bvxi/Wz7d1fduPZWvjq2fUB/nX+/s+3a3D7STx+GRH46uhj+PJSBI+PZuP4aDZ++TSVEEWv/kjf",
	"//nsMlg8kesmUK4pfvtxvPE2PVusu33Ts5dvN95vXK0Hj4+iAD+ZBy/fpsHGLDkjf6TvN56KN49fR+/f",
	"XYlg8dTth99sv74O3+3Km3Bx9m59Hv65HwX5bfhlN3odnZHXUbAxlW1niGzJtpUx4Ls/8AHevdrfOIv2",
	"d4L1g+O1n/d23j95c/LH1d7HLfH+4368t1i7fv8xWNu7Por2Pp5ev/94qvq+33h6eXYs4aNgmpxtP5u9",
	"f7w7DeKn/OzPvWnw6vX8LI742fGzx2fvdsX48evkbCNKg8Uz/P7P/eT94lk0fvciGW+/fnr68emTj7OP",
	"15frL54+xnQ2Pfsn+mX26vr1f//3CVnQJwfv/nzz5GrtLKR7awfv98P5y6Nj/E+69jw8FK/Ff//z+8ba",
	"8QZN157tH/3y+x8X+2Sx1T949/nglaHdv3w/+MvnYXa716lu0/LqhlbLu5SLW3HoPttKj1vfDVepa1S3",
	"4c5LJG4JcW4xJuXHMHP2mNtjbkuN7DbsVe1uCX/7OJbbQ99eidvHrnxnxt628thtpMqEptwSsfomgk+W",
	"8A25N9rUu6H0tLCP47t1PUZbZgGl4s/D+orKfksT/ZLZzWL37lQ+60WjXjT6sqJRuVRbd0HpttCpF5d6",
	"camnI98CHUm977GSRpZ8kl0Z5rboSC/J9JxAj8HdWG7tKtwpRD7EXGASiMylV/fNIr9zVM+RcZGgulj6",
	"N3rmDtguRzFethmOM7OwbBGMxnVWigtMwkaUtxHkphZql+jxLTDBkfFAL6+FkmihfdCziFIgZtD1M5/i",
	"OSK6feY6fSd+2bewSu2S3LbKW/epzq+bXu+9hOTfTAxDVzBOIt1Dr/a5/kXhtLGMbQ7Mj7lHt8ScyKKB",
	"ct3WSS3mmFESIyJ+SxgN00Bo9xqGppiS31K+giAXK+tyAxix38YwuEAk1IjdjYQo5Ov9pn/4eHl1+4ov",
	"AkMJ5VhQhlFL1PyRbbloC50/csfsA+j7QJ8+0KcP9OlA13IK079VP3iMT/YsLbpEsXueprpQ9rzpHcWz",
	"OxPcc1B7eebepNhHtn9RvK1hM5fxXO6E2bp1AbOX0il6JukdmXtN37ej6Su9lg3ezJ3w6SUSt45M34jx",
	"vPkN7bHpB8SmFg/jThhljMe3jFO9Bf2W8bpni3tPu2/e065MvhqdjjtRL2O1v3X69U1Y7peV5++XZvX6",
	"g55Q9oTytnUVxrq1IEGrTUw3PV6QoN0qlrftzWK9Waw3i/VmsY7vck44esPYD28Yyx+nbqYxzwtVbxzL",
	"G9+ZecyZ4t4NZOW5exa3N5F9YQyuYzyXs5J1QnJrJysg+ZKCvGei3lbWy5nfkna/9IA2Wss64ZWyl90B",
	"Un0zNrPmZ7XHqx8Sr1rtZp1wyxiN7gC7euvZrWN4zzP3auHvQC1cJmQtFrROdCyzod0BJftG7GjLCv73",
	"Tb96VUNPNnuyedtqDZPAus6MJgUtrkd283NXBKw87fidUYkOubZ/TJ2zPcMPqqs26egHK2XRYHOwOpCP",
	"hmldPuADe5I6dFwSBESE2cHISS5b+DCo2qKcgSgB24gJPJGt0TGeEkymhroVzbDWKpm35ro1y2hh8zw6",
	"SNw7qE6d2zrC86xqfdMKq7XtG8eVoDQh3phMbR17ZzhVGbltaZ5CyIU0/MsswcRtw4BRzkGIJxPEEPGP",
	"ruNQ21ZXF3BqBnHM9+0j1Znps7Ec4tVh1wHCatMeymVGtDjz6cOn/z8AAP//HWcFdP4OAgA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
