// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9i24cN7bgr/D2vYDj3FbLcjJBRkAwq8iOo41fK8kZ3Im8CbuK3c2rarJCsiR3AgH7",
	"D/uH+yULHj6KVcV6tNyS7bgwwMTq4vOQ5/C8z5+ThK9zzghTcnL450QmK7LG8M+jPM9oghXl7Cm7+hkL",
	"+DUXPCdCUQJ/kfIDTlOq2+LsdaWJ2uRkcjiRSlC2nNxMJymRiaC5bjs5nDxlV1RwtiZMoSssKJ5nBF2S",
	"zd4VzgqCckyFnCLK/pskiqQoLfQwSBRM0TWZofMVtEaYpcj0IDhZoXUhFZoTNCfqmhCGDqDB4799hZIV",
	"FjhRRMjZZOoWx+d6+MnNTeOXaQiG14Jf0ZSIs5wksOUse7WYHP7y5+Q/BFlMDif/vl9Cc9+Ccj8Cx5tp",
	"HZAMr4n+bxU4ene47I50K7+3g//3f/5vdUco42w5RVJhodA1VSuEUUaUIgJxgVixnhMxBUgknClMGWIc",
	"Xa+oIjLHCQkA4k4rApA/J5yRAds+WeMliQBvcvP25m03nM8UVoU8hxZ1kJhviC8QRpKyZVaFEGdIrQhK",
	"yRU1GyKsWE8Of5m8FiTHsKmpHkMo88/TgjHzr6dCcDGZTt6wS8av2WQ6OebrPCOKpJO3dcBMJ+/29Mh7",
	"V1joQ5F6isYOwjkbH4NFNL6Vq2p8cstsfCjX3fgUbKQKaHlWrNdYbAYCPMtCWMt2YP9IcKZWm8l08oQs",
	"BU5JGgHw1kCtrraco7VJMHlrmwg8qw38cjXoCrU65mxBl0046W8arxZ0qUFRRW9cqFUcvNBNwyGCfVPo",
	"9+b0eUu3N6fP4zgryO8FFSTVAPRTl6PF0O97rJJVcx74GVGJMEMkI0CmKUNz+FmS3wvCzNFX95vRNVVx",
	"erbG7+i6WFtypAlTTkRCmMJLom+ZuU0SKY6KPMWK6Pn0NYM59VTD6M9rPyoQrTVletrJ4YHfPGWKLA1B",
	"mk4kyUiiuNCL7hr2OZ6T7Mw11h2LJCFSnq8EkSuepX0DhOu6aTuIMwvZlgNxn1FKFpRpYK0IyqhUGoAA",
	"JwPAOUHkHUkK/XJS1nFesnW+o+q4ZkZ46OEBpYqsZd+Wzd26mepDODEdylPAQuANAFIJrMhy0zfaKc8y",
	"Xqgz17x+4f04sWt+rPe80IhOzuhSE9lTvXUZuaytTZEguSBSLwphJOyPCy7gSVoykqKk7IsWgq/hgI6P",
	"IoQhpz8TIWHGBuhfn9hvlXO+Mr+RFBmI6LNRKyrLZdmncKGR1mx9hs6I0B2RXPEiAwbgigi9lYQvGf3D",
	"jwb3Bq4TVnpbGkkEw5nhrgz3sMYbJIgeFxUsGAGayBl6wYXG2gU/RCulcnm4v7+kanb5rZxRro90XTCq",
	"NvuaCxF0Xigu5H5Krki2L+lyD4tE8ySJKgTZxzndg8Uyc+fW6b8LInkhEiKjJPOSsrQJy58oS4GMIdPS",
	"MoseZPonvevTp2fnyE1gwGogGBx6CUwNCMoWRJiW/qQJS3NOmYI/koxqqimL+Zoq6e6LhvMMHWPGOHBz",
	"htalM3TC0DFek+wYS3LnoNTQk3saZHFgronCKVa4DydfAYxeEIUBky1/3NWjFbuAuQZyoF/f2w9jujde",
	"wxLf7FUJNmlXvhXdeE63oh26ubmHjqy2Nh2Jxd0TC/98VYH5fMjZDHr62t+bm+YLOJKuD0C69FkbwrUd",
	"qTDHvxWtcHqD6vn+U+A8JwJhwQuWIowKScReIogGKjo+O52iNU9JRlItcF0WcyIYUUQiygGYOKezgN+Q",
	"s6uDWecSmoSFvMupMAIjSThLIyhh+xsVjKcZVzijKVUb4H7gxpQT62kWXKyxMrz2V48nTdZ7OiHvlMBd",
	"CiSPZ40jruNPTbOkB0ZYmctFpCF9BMCL1Aor5GAMzJmGc87zIoOf5hv49ej1CZKAMRr20F7vXNM1ul4X",
	"Cs8zEtEjmYsU5SrPQZKR5Juv9whLeEpS9Prpi/LfPx2f/fvBI72cGXrhOPkVQfplmnlek5IMOHoc3ocu",
	"htVQhcqRzDeKxBAHWFjxMqqQOmGpuWSwJuHvhOljCD6Qqt8LnNEFJSnorKIIWtAIsXtz8uQezilYhMRL",
	"Ernub+B3gLreBlBfAm/CJdkg0yvYvxVRqZRFlfuvPBS9F1hvOa4J1Mdxj4CpkUJ3myuXYzvS57m5tguF",
	"81zwK5ztp4RRnO0vMM0KQZD0+ie/y0CDKVvgjqhmaDaIvKNSySbFC5rGcdQO2ZTnpiXgENcyuIf5IOzS",
	"5NWIzxGu0X8zejZ9sjzEtBn6ifFrhpKgoSDoCEBH0il6QhjV/9UQ+gHTzCxqGKfixmxezNptCLYQvQN+",
	"oPYNlseXEoVpJuEB4YwgrFFOueNOCiGAA1H6TB3vqi/1aUDSaronLNW5wEzCTOe0TbGu2yFF18TM5Jem",
	"fF+SGr5Ir8teQ8URZlytiKictmaA9vRYcU5EanrRXMWPxRozJAhO4TbZdoganNB8nYMOnvNC2RX75UUJ",
	"Gp8DuqfPCCPmnY7vfuZYmdnStzREpQqNayyB8uk3K0VFbqYN3/Vvvo6+64JgGRVU0BdzQcniITItStbB",
	"zflADtrpQAHRjeoEQjfSwG6gOq1jgDL6VLuCaezKeQCU59+JLG0E8qxC/jyMpnAp+QKdCy1o/YAzSabI",
	"6qpDVbz+PplOoMHWyvfa6uxYtV/d0LWfQ715FZrN+7jJYS/lraOhJBHsxlE6o7B3/zRUD3apSZ7+CDpZ",
	"Os9I/Q9HN15jIaHp2YYl8I9XV0RkOM8pWzr9rj7bnzWLqzsateMJey34UhCpv73Rko+1KeUkcU1fFJmi",
	"eUZeXTMCYzwBnfYTooUeKrVIoTsNO4OnTPAsWxOm7FMabLz1uR3SxkOttYUH5ynJuaSKi00UlhqErR8a",
	"AA8/euD/kBGiWk4AvjnYwh+xszAwDk7E/BCei/ll6OmYe7ugy7rZd5j94RlVke430+5eP3l2/owkgqit",
	"Op+wjDJyi1l/VCqPdQMY5IU7sRec6Uuwnfk71tkMLDh7+i7XxxdnFgRniPgGyLw58FzosdMiA80HXRM5",
	"u2D6TbMtqES/fYns/347RHvoBWVaAjxEv335G1pbqerR3t/+PkN76EdeiManx1/pT0/wRtOlF5ypVbXF",
	"wd5XB7pF9NPB46DzPwm5rI/+zeyCnRV5zoVm1TXzgvVd10v9Ta/YCX6agzXani/IbDmbwjCUoZVesh+P",
	"XBGxgd8e6nl/2/vtEJ1itix7Pdr79jcA3MFjdPRCMzHfoqMXpvX0t0ME+i7X+GB68Ni2lgo4yYPHaoXW",
	"AEPTZ/+3Q3SmSF4ua9/1MYup9zgzlvrqXr4tQaLftm+DLhfs6Tu8zjOiIYce7X07Pfhm7/FX9kij7MBx",
	"IRVf7/6qThsvspEJrcOB3vPatNfXMYFVoJjW0T36+u4bktO88+b3qoEpX20kTXAW2NlHtfBoQxptSPvl",
	"Cz9cHrB9bmEdirHvZrSGw03TUS6u1akJgCxQ8gSONlGo6k6buGjnPCsWTsrW1+x6RZMVaAugp9NY9U8D",
	"3mQRweSln8W1QU729CJdfPRASBx2ZnHXsPrhAYgdYIKV+1kGHWDV+ScmvkrTwB3UCvyQgFJ2+kZV74NG",
	"x977oBtpjsZQb4Vp5kgMyMeh39tOZOVuz7Cmn0UPVA1H2QbI40C1Uwq4Bl6tflSCsJQIkra+d6e2gXvh",
	"WsftU3hW5+ncpORZ61NuP4cvupXj4eeEM0YSK/L6w4755wAPfPIkjvH2Mzp5EmpTajPEL4bp+SKg0bX7",
	"7q0yfhZHER0N0eu2mvHvKl67CWbwLEmjyAS/IZzRP4zGTVmpXxGxpgxnU79m47mku00RUUnbceH0Fcs2",
	"k0MlClK7mrVdTQMAth9lKAE2AeEGs7o47K5UWpUbvaq2cYYKiyVRw96ncCnn0C+uhzJDDttSMM5hC09r",
	"ucOUSD1DY2trolY8raJUqJ15wwgoK0ATo6X3zSmRlfV1KTq6VhyM3NWsOquHwol+cARVrUTdErsaLaKu",
	"W3PH70nMzRXyhLycaCdkPLppu8XbUfKOsXoUlh0w9J7ZWMqq9q50ZX7DpBOTt7pFtQX7KaJf/bzRr+Vi",
	"Wj4HK/QAe04XJNkkGfmR80sHJ7fh78mCi1BTdbRQRAR/mwanZM552KL8YRtQVJbSmDrSpr6a1mHCBbaN",
	"E6y5CZxbsQaZ671TPKwPbud+byys7fV26BcbpA3v/KvaArGSVrtrbRTMFgGqOtDqL1viYG3VdTyqfa6s",
	"IvI9trSeZjWMjHljlN+qTnnmdznqWj64C15wEoPM2FazNnrXfWzeddOJFZyHnaBjMnbnlmfGfSXjXnjh",
	"V2Q+zS0CGy4bvTrzwlUrI7iO2vnPK4NAI6vrEcNieMy4nZu6zVP66mzwFn6uitNuG3GM1l+e0GWr/1sK",
	"3+pjGbsAkiv8+G/fHOJHs9ns4VDQVCdtB5S3PW4FLk/A+gSBJC+G3e7qOgxXMJ2kVF6+T/81WfOh+BUb",
	"oe7nkxcTP6hd3VDQthj6rdgvrdrQEFMDbEPjmxGE/8TCPvjHgiqa4OzWsYSxhYahis2v5eSxr8GCYp/d",
	"ImPfQu+IQI3dQpZqRAl3mIJKDV77mxoqDnNr8B3+wrYFREee3KQlVtItxHy/xRqiNu7Y9JJnMffO8yBe",
	"DieKXpUKM6sp2pbjcHrAqFtylXXdWgMEfl0D12HfN6O6N1QrwqnqpVVw0Jow7YlYD+/hMKhZTmNQkBup",
	"yDptUWCaj+Cq6qI/7ZKalxyMxq+x0oyu7IpYhIYoty0rm2ko9Y2B2q1D807wRE9NHD0X8F8tLcpisaDv",
	"psiE+61Ilu1JtckIWmZ87iaD9cPseIkpk8p5MmYblHGcEjMFrGmN3z0nbKlWk8PHf/tmOrFDTA4n//sX",
	"vPfH0d6/Hu39/fDiYu/X2cXFxcWXb7/8j9ir23DZbNBpw0m+5hlNBj4Sb4Ie5lrdtNL/tic1/BqqweNy",
	"uAzC+y2RQ7av5qmVwDQzpqVEFTgrHUPflyZaligkjaUKYAs60LQFRnABNw0tW49eM1QNdy32ZwBwNDY7",
	"Z7TScIz63YbgfV934vBdGERYSyuS5i6d/u1WalA9QoalOiOEDXELttfCeMES5tzqLZ0a7gPsdTC3Uhtt",
	"+QD4PpUnYFuecGuRrXEhDTU9sVq5AQOU7T25SrehVGmLXT/AjMqqqpg4iSNmCMbw+vlrDGdTrreEWnDV",
	"whvQzkPf3vYc3NUVFuk1FgRUP8a3jLKlfdqqnkm7t0nbNThv+d2ZM3Zgj94q2UncVvEKPCzjeU1Cdfhr",
	"fk0ESV8tFrcUUiprDWZtfAsWEvlaFUEqn5ra+8rnyg4i3yMCTAXbo0yAb2E1biaiiqZyvyhoanJ+MPp7",
	"QbINoilhii42nQI3XhKmWhWympwfLSGzlGkSz7ESqMJaxgha6OfTuG3O60trjKwBHDPZf8+5QidPthnK",
	"47GBYXydrzyynzlkHzhBXccWgsTvo7mKafUA2lGvwUj2WKBzaGmcKzHDSxMLA6TFkFnICZZkRaq/XK8I",
	"c787hfmcoJRfM8tsa1JoQ6qal8i1OzNexb1PtNmMb+2fqtv2v+kBW3or5Z5Z0+6N1ZXhd0nhK5u9HYVv",
	"DrGFmawEmLeR5ef8CYY4vleFerWw/w5so7ch7ZVFBlNEvoazRjvXjLTVrw0KHcoaPZyFy8LkXHwyQhQS",
	"RBWCkdQg3IKoZKXRzydig9iMTgGsvMlt0d4DIstSssBFpiaHfzZivo/QXBB8qTG6cyfzDboI13UxaRp8",
	"y8sl62zZR7B4u6buhSuucNaihtWfAlfR2EwDI/0s9fuYoGN58S7o1F2pAFTTyGWtn39tw1FqROXlh45E",
	"SKm8NIHqTYzMsVq1mWYExF1tkG4TqOFg+OqY3TwEzPE2Hv1ApShg1u+L1PrE1fjFWotqojNyRTKbkJBf",
	"k1Qvy7Y2lEmY8DDNZFLQcEOMWBMMS8GL/PtNu1Iow3OSoUuyAdY0JwJcHaGbBrE3B5bzz2G5FS1JoM/7",
	"4pejvX/hvT8e7f397S97/t+/7s/efvnwH8HHARo+UBy+YfgK00y/2S3Z9kzauwDR3Rkh39PjkUuuasAH",
	"usmOrHnw9ahn+lqyvwUqWHNef45bzR9lm4ow5tnSkskjjbTti/MJTdw6vPu68cxVHCU2g6ZJOOs7lLym",
	"SxSRIgwxO1wzRVfW/41o7LFjzzcIG/VSwaiaoTIMzP8IQf2H6DdpIqqkSckyRb+tzQ8mSEr/sDI/QDgY",
	"XO/gqv3j8JeDvb+/vbhIv3z4j4uL9Be5XsXvVRlhWua2rKf5dS32rOarj6UrxzyzHer0ITJmjJQ2wl+b",
	"F63RpCNBn00yoc/ULKBTcTz6+oxxVZ9hXFUDobYLsWp2320uvpaI+Bin29q0TEASF3U9oQhsH6gkWe1e",
	"/thF3nekurleEbUiIszsglZYojkhDLkBgjOfc54RzIztYk6y98m3fuS0bmYkSGiS59nGkZaGiqiFX/b7",
	"3OqEAiFhEB/cftRNbrhn0r4TDyyP73v2Ry1+T/DCY2Vj8cLTv8aycvDDjEqux/dtgYDVeELdVgxQ/pWj",
	"TsMtRXj56ZZHcAvzbwTw/oBm0bsW9/SNNqs6/TaajCzBB3f/jZ7JIAN0k3EcfYL/qhk34wxLPw0Avzpq",
	"HOp8Q0N9Gm0fSOfDC04REedPKeJkOJbfMUxVJ03SnfBdiTziVR+b4SHud8EzuDRhVnBD19SWhrBsBJXe",
	"cWJFGNI3OSDjVMaYnBY+Q0N12JG3GElaGm73Fg16Gkom9FYsTeDI05ecMLxRzQyFs63zDjaz7JH3oLw7",
	"yyTYVCJ0nK5t0sXmrfi1VeZoQgi4Z6vk/JDR5UqhY00YeRZe1sDTp1nSQxPHxCucttKHHBUKSiIEapCC",
	"7rm3IH7sb06fu9N5c1JiIdhgUSGN22Qu3Fvyv06RviLAA2SUXZr8PDCfe8E6LM63VfS06Xtq8ConaIXB",
	"oCsBcOy/Fq46S5kz1L601WVVLo2p6HCLq2GG3gtQci8eXH8MDYP8a0+wwuUyQzSH0HPgGbBbuh4fLWgG",
	"Efjo/PlZHPHNYi7JpnMRP5HNVpNfkk3f3HVkb4FKc4mDDn44SRhAGVyWBI0W/JaHHuxLXyouqGoFedn2",
	"yDVth37IK/iRUSXldxsCkwhLYvhR/QoD8UhTQaR3HujdOPrCsZYrLpWWMA9zLtSASJ0OAPnFRk9e86BN",
	"nTSE+v8q227BUaH4GjIhu4Vz4XzgDOUUdLmEVCHAhOtJ0BfUB0fMMwJ7YkVm7RsmzURTCId1FDIG6jeS",
	"CHS94jubLOFCkAxu7q+x9NnH5XefDETg5NKwlyYzNMwuEU4ElxKtbTZE5ylovf57V2Iz0/Y+D3qyJ7at",
	"FvdiOb/B5cs5fFEivAEGllrRhxQFZHIcnmP3CK2KNWZ7jSy7NpzGvYR+qlgKJBDwfo3ncGquvhY1hrCU",
	"PKEAe2A3Bk43JE2tsxO7CDBJrojzjY6liTFfSwtqZSnO7YUa19hrH/uUuDintzEyAwuIT+hXDMhn8RCw",
	"zyYdDhEiXIJtu4dzWnIKezkRlKc0CX5SWF5OnHi0B5xQfJUDXKhIBSLTMA9zqLG1VsFrLL1ZMEW2Ctii",
	"yLLNFC0gowTEiFCJpNLiEWdLTtmyskvTSd9vk+wc/Iv3nME6uhHId6nwOo9A3H0yUldJaXgC/vxbaBZV",
	"Z57exnG5a3hs8tEHSV7feKdo98sTYkoRxjK5GH/a1oS3b/ueGJeX2VzJIEGzIw8BhtQRu455Iahbn6Un",
	"JRWsMSFXYNi0Dhouj/cUSSUKULCkNqM2Z/aQXA3AYdlla/D1FDa20h9oRl7lQTZwd2yJPy5B1jZdsPNi",
	"H+bRVhm6PP3Kz6d+7MrP7ma8tSt0KpsaV8WZIm3yUJ5hypAi7xT64s35D3vfPtQYV6uuYUdwuK151jYB",
	"Wbd7qrvZKL2ai6SWHk1mLWVeUEGQnWWGXtiqrIQCobiYwOIuJnpFFxOzpovJDD0xXgkgqvlGIS7BT5Op",
	"7RKlAeCAEgeJ3t4DaVxUpoFXgl0WOCe40HNWrImgCTp5Ul+W4FyZVTUfWp6SzqlzIiw2Q9maGfovXoDu",
	"0yzGOCKvuSBogdc0o1ggniiclQVrMTj1/kEEd6liH33z9ddwttjo6hK6th1MKq5Yn68fP3o4Q2dEFTTd",
	"l0Qt9X8UTS43aG59LJBP3TNDJwvEuCohNjV+yNXNAGOi9ylRGgBMLy+e37Dd0QrPJc8KRbyflbuctcyB",
	"6CVX9s309SzA90g3Bb3bnCB+RcS1oEoR1lLlhIjOQ+PXUL5l5/cl5hPmUS1KVsGHtLnWH6wDauDXYXWS",
	"6ZiqZXTfGN03gh6AK9u5bJguu3XTgDHjxlj/qWqAhZ9HTP7wVtfyIAYp/A3NHs2rf1Xzalhzo83M1myz",
	"nYXNRpiUrr81OcDI6S1Vys9deXDnaFxmW5gT51Ksha1Cxfi0m7Y9x83I/lOL6Ri20msutlsdlo7htNL4",
	"fcqVK7LOs1bDovtay3TVDAupZeS4lxTv9Wiw+MNTVwm4/bZe7M4bfeurPDhtBbSeIgK8N86yDaJlNE6A",
	"Git8RUBEARtB4lRnEB5JKhp6qAt5vaKxFJlbm4H9ib9/1oe0EYS2TRq4qcOYQa9RlVptaXeG2mk0OSU5",
	"92E7Uc+JBZTdqud5HqS3NUM7vW0hWsK0vsg5VFXSvMSaK/IQYnpNLaZhueP00LZNdK/RMkUNPcySqlO9",
	"ndgaBVkQQVhCjO3sGVXVNEK2AGWEbPCCqddeRHbhGvuNaA3dxpEgc4seSCMBW4tOzanSQeiBNOJ1GacB",
	"U1b8TsoHtl1YD2V0m7PKrqasjNWizHef+z00y6Eq9Vqbull4Vk7JFW2Pehf2K0TUS1JyQ53rbSTB94tv",
	"zDpti++atpS6qO+2lvqrfzVWSWsvYmxiSDqcOCVn6WBci39edGbHAU3L2irz1kRFgoHmBJF3JCnUFtU1",
	"9do6iaOia2KJ2ycWqYQeyAfVQKUH6wfVQCUtDz1YPXj/YKUIpza0Hlt5O04LNrl5C5GI1R8jcU9XP2Px",
	"Pq5zT9kVFZzB+3yFBQUT5CXZ7FUKJVCmNxNEwBVMwzheWbpgrca2tQZ09YaGeRIw2yAslsUaGJlCQloY",
	"hVmKRWpSmSG5YQq/05dHy1BQZtoqSQNTsZ1JopzmUNphCdaxqb5RFNB7g66JKBeBCpYSgTCaY7lCe4nR",
	"ob+LG0Cvubh8Qlv0lfqjiW51caplsQgb/Fkw5iRIu9ABpK5grSSlUs92+F3z3fTj9Srvr8EX9gnq4t30",
	"rquriN5RpYReSdyIvn+QwIEjJQqCwJrpym9GaZ4Nf215PGNbbuATb7FaeN+DL+RDpOcHFTsGs/GcZNbw",
	"Yl5hvQWJFZXWlAC/+qUP11lUjGIRgryF6h5bxb0Ir6UHNTDuyQqzpaG57wHmuDqdxw2UZVHHXga28RoG",
	"zJte5I/n569Nqg9NCSJSBZ4lIvJ2fQ82LGckQ4JzhY6PWpgvKa+5SNsYMPPV+OQVamWsRc11efO2Hy/m",
	"DHBJc6M2+pkIH0Af8ZS6pLnlu10R9augQzxCS2VyEDDOn58ZDz4owjx06Xr0S7IZPvol2QwfnF+2ZcWD",
	"T7uBfnuR+3Nb3B74xL65+jmDSUtZ0wZZWimVD5RumFnJMPlGU4XXUTLSK9AoHgg0zoTt86/YdE6wFHBo",
	"CPi7LjvgNuKIaIojTprARscuNyxBHYKKyZQa27zw5vg3p88NqUz4WpP8hbJeNnMs4esMnSgoJGXYGIJ+",
	"LwhkpxB4TRQo64tkhbA8RBeTfU0R9xXfd0rff0Dr76D1EANlReTxx3f/Uo67kW10/ZaqiVXlSRhWEXho",
	"xfTBKg24tXDuHCU4y/S7mWScGSk1epOucEZTk5Ol5U7p8cx9M6wgZ5lJH+a6avYXvK2cHF8e9Qy9kWBB",
	"ANdXfcHdzTQMMMhJ8HbZVTt+c75xB+zyw+uz0Ew1rIRIy0eDmX5Fsrz0/yt35HM5KpV7Y8VWap1peK6x",
	"G3OyxksSSdvdpIQt2f9PQxroKBIUlrSp+yMFH1GOk8tBmWLaqxu0FrRuLtykSOxIBm14Sn3nwE2pWaBx",
	"MNvYlm78bkmC3WEMTJ1FwweWIt1+mdOJhNmG6gXLVSLTsVcheHsVoJlgoN5vGEDKNUcHkDlOOkaBz71D",
	"xU++HH4aQKjX8mF7l4cUuzpgH4ob6UvUScHnKFE2/m+qBW0t3eNkhTTWICpt7XVlRJyLia8FeTGZXbDJ",
	"dEJMPW+T+cXrRL7LBU+LxEYECbKknH1XyD2Cpdo7AB9MIr6b4+SSMPBJ9Ejamx2pavmK7Q6SOzlDmvVE",
	"gN8Mi8GvQGVh3YxKezoyd1sWWZlk/rkJjDR2f5WsSpHcqMiOXj4h6Qw9Xedqs8+KLKvNbou5I8bVyjoJ",
	"R3LeB6P20akX9faQL8qv9L2CQdc41xv/85JspnDGN0aPFQ/mbF45Z5+Ouh/oL0GpC19r1Mj9G6ZWRNEk",
	"KMniZexQ06VvrjmOKywoL6Q30MEy5AwdBbUP8MYI6cA0aEZE7660VU6RW9hN1KCmKCsiqP8Cb0DfSpRV",
	"ioFsA39jlNE1Ve4NKrNjwfX2fL5RnFKfN6QSd0sE5AwBT0pTl9Tl1TI31CgYqUQ8x78XxPukhAVZpYQP",
	"HHz9XHYF+8QHfhPY2BbB4kilIQuK62UKSq4Mu8TIO+Vwpczw5cF9bMBk0kUmnEkqQaSBsfSyrOuFNXcR",
	"BzK706q8pfftFCqQ9E6AhyRDGC3ItVM7mzPNofSjR1o4cecwZNi7alZLoxWFfbqjtaB0zpYm0iMxSaRU",
	"CWlrIacCElDJnDNJpqhgmWY6N7ww6xEkIdSD0orVEFnHEBFCb8f4qrcIcGtMGWXLE0XWx/ot6CsBLou5",
	"1AfLlL1cdp0A+LIouAa/lbBS08QdtNsKuMj6nu6yOEYwtQQN/GNBa+woGzjS1u+534dblESFSVcK99QA",
	"Ug/jgJ6RhUIFA+RhKeJrqgJ9uSQCCgsbtUxlobSM0kBfWK/WOUmwZvMpfAab+qpgoFfm5VcAgY2Sg8y3",
	"0OhhuR9BLOjMDazvyWzEq9FvtRPn3MSzFORizNDVwezgbyjlxl2ZqGAOc8spU4RBhREZCPP1e6N39iWR",
	"iq5BOPrSYBv9w3olJDzLbNloZAJEvVecnlcQoJRtYxsZCaiB8PYInAxLKBp7M2rPWZOpjerETDkHm8Ix",
	"pJ72yTcZocH7qz3nNhc9OusyhRIQEHhla4E+J5q7eckV/PfpO/04TaaTJ5zIl1zB31E/f+Mq2F29yLTx",
	"9WYqgkx/jZiQX9QgDDb9tgn2AcV2SmPDcPfB+uGazJInputBk7N7ARXJdp9fVe848FBq7LX8ppGnypng",
	"LEO5flakRuYod2KIrSWykPTSPY/AGNi2RjqN+MAyxlVZxOaWzFvZGLCzWc2kgXmwHsrZeUfcmUttZerJ",
	"gIcmRMeZeKDhUWcpycht5rKUNTWRZcPns0GIccMZMs9m4p+tin8qRj62qxylzEts6qcbzz/0mueFCb11",
	"8AaJdYZOCU73NNM5MNHyeydyeWE4d+t2C3ltDY9saAjoYas1+7lYYqZfBd1Oc6FLLvSfX8iE5+ZXQ04f",
	"el5vcmttqXXDjtLia0aiUlzgH4wV4tfgwgF+3uZ3LRVoeZSydF/PdTGxompn8G27uzlz/LQFIkzrg39l",
	"wLQ+kIFfeFk+s3Q3H2bEeK2pY5D71JPULfS+vXbXIL1x+G7h1AQH5pnRPpgwwehbFTeXHqH/efbqJXrN",
	"ARJgMG1T8BYtF8Rw1/qNTYHbt6uZNd4vnnd5JdUfkddEJISpqLqz/Ob4P3vY5uZUKUFeNjatohusaMcj",
	"+tXyq5syrFAgKl5b7nSWVFndb/RETjuMPRVfsyCm6hlVoeFH80jW4hVqpsfojDHOaoyz2i+RaLtgq6Df",
	"biOuyoHjGt3q92rslf9Gx1jKjyACS9SOY2AVVk/xx2Csv2owVo3qdCB5o2p0VYtaZSqGOTbWIyN6nRpD",
	"X4W+xmdyVbbt2XpLzE69xXaBO1WIvGfgTHWw+02c6NQbRxkR6tSWJKsVPQt30Js0qRbjBqZ+PXY8V2nR",
	"JlS78hyex9WSPNjZStMtviJCM9NQZgbsF3NrfJiThUZ6mFjz2egHOM/Dbh/2fu/0Ls/0i4v0P9srZ+Qd",
	"QsS5SR/hZAO+sDsKk4/JKCSNvqGezmmIOgvO+8x2ipdQK9Pf+GOq7KOqMui9XJXJIqnmbMKp+p1xIky0",
	"uD+UkByWf6Z1LeXArU2CGVvbmKUEm3YFzvVWqd7qmjKnI17jPLeZY45fv2lF8ryIaR9N0ajWYLiWglJO",
	"GdqqWm1Vld54Ard5CcqZiS305Py3hj0ILbvpI/Vd6+oJC2yBxE3klDorTcarZuFK7FWNCXbUtKuiPjRC",
	"QreaoVfOoGx+zcH8a1GC+rpHW1fZL8l6rCpUcIxx9alVLIRenUGt/aaXD17nGWXLE81iR6tseLI+J+qa",
	"EOZrhkFXDYh7oNQ+gKgjdiikhCGcpuHZRnbcRQbPNizKhZVf6+WIAq8ocDawFmzjoAbBu4EKRnHjZwv2",
	"dntgIGZRn6txFNVGdcyojtkPUW5bhUzQc9cqmXJop5QZ8fUDq1Zs5w1Ltn56gdqPypW/rnKlRkM6H/aa",
	"gsVl8PtCPvTPtk2a3qVZ6Ek7YFKANOILKWtEMZxA1STXYmpLk7oOJdorTJnxdYxxFCZGgXF9dVxvqnH6",
	"KU5W1uO6OpQxebsB9IJDtqYbV+83ImlI6gRnvPcpFJqQvqvMCZF3qPv+3ULHFfZ/Ty0Xvh0p7UyD4JQ9",
	"x3y9pqrNpQscD3UDtMLSxgRfYwnn3+Lk7wZ+1uHz4QcPXDoiYw/xYLuFsq7NNOxuuiaaiLzLudQPLcVw",
	"tEevT0J9SlBY4MxUFXKeA7FKqi4F88Sl3awYjWsiznRyblMpOdIaNzpH8xI3uB778PwKfosdj7X5bk+B",
	"CP9ilVhZoru/fQ4axmnE+8002LSBjnG1tUbP0KQbstmqiHWdjEjK/rGwtWiM84zP96SF2yAHWpeKCVKh",
	"nVkfpTZcqzZq6nykEliR5Wa4wqc2YgcwysxmtRsdfnaaYFeyOze/1pNP1XXXkCrI3LHzMnFKp96oKEP9",
	"0+YxDUi+Vj/cGzifRiHzHuVVtT1EyUJY4vlKELniWdo3RuC4EvUX8pmv7MnGKwHYrxrQyYrTxITw2aJd",
	"0u1RY1n1ZEJiU70KMbQ6k6sdZSA4O/uxKwFBLugVVuQnsnmNpcxXAkvSnknAfDe6Jrl67ft+HAkEKkvq",
	"DfS3OwcADY/1j12c0Py2nXuZDI+5x8J3R0HFevs15yUXYtwVWtwVVFvuKkbk2vgzy5NRo+pThWBW6NO3",
	"LcGZK5+XcvbARfQjE4ATOFCOKoK7VREk0Sz2Z8VyScCBG1ze7OEkLvE7wM/w0lP0CNGFC8GoM4VfPY66",
	"7446gp3qCIYW/InYrkuByMDRucG2iKhYxo3ka5ysKCOtU12vNrUJ9EFbzvVi8oMp+nIxseuxgUtUlrF7",
	"ZJ2rjY01glClqoRXRvwdoVNYJkoyLIwnsvPclK78dUrQvNCUh5igJ35FhKApQTRux5fdJM45bXvgoVcQ",
	"OnmILiZnhqlx5S/8Tu/82mgOfw+zdM+CdEC166aqyJeNATLhb0B56WIPQl06aj5T1QZVq1DoIO6z8I4v",
	"wWjcGY070KOGPNvZd+qdd2viqY0ed72NNKr639YajFzghzcUxY5kkIaz/hSM9qK/qr0oRpb6cL/hllt5",
	"+60Kpp0FWMQLJJ07dRm6XnEZZPK3+L4Ab0PezxCZ8Yds1tPeYTG3YSr/6Z/v6167Zd6mTqODvdVHqiPe",
	"tJJeyAP3GktjMXCIMTD2dBsLwdtpz326hRXIb8DevRmcL12Tf3GXRctlY3/OjY9ks9Yk+oOzsPCptN5c",
	"MNvJ0csjFy93dPr0aP/5q+Oj85NXL132IP1jlQc2+TZstVCeEMzMG+J6+tTVkLcaC0WTIsMCSWoLuVNr",
	"rsGC4Kmpdm6yDqEjqFyG91+S61//i4vLKXpa6Pu3/xoL6hz1CobXc7oseCHRV3vJCgucQDpCt9da0Tj0",
	"xcXk2Yvzi8kUXUzenB9fTB5GyZPRU58lK5JaV+y6UaB8saVt5dJfcn2MCUr5Ncs4tlmcU3vdZJjyRtG1",
	"+8pzo7hDNql4hJfoVVUfi2oWYuC1hHomcEKeBA7eQ3XuKrhcnW+na9eg0XGiFLBE1S1etfFKz6gKSW48",
	"AL4FUd2gb2/0FyiUa3MA4QRAStaYZpPDiSJ4/T8WUEw7UdmM8okLggaSUiuzfU7wemK1mxP3glZ6N0K5",
	"f6kO8faLWLeHlpmwhUGMij/JsD6Wq0rtEL4wrwfQB5Iuy8ovNh8LFZB7W19CaTJ6ZTQhzKjZ7c6Ocpys",
	"CHo8e9TYzPX19QzD5xkXy33bV+4/Pzl++vLs6d7j2aPZSq0zc1WURpNJDUhHr08m0/JYJ1cHOMtX+MCm",
	"6mA4p5PDyVezR7MDa2SHe6AZiv2rg31cqNV+4tXUy9gj+owoyDlrEvwA/azEzMx8ggzK2Ulqyow7LTFE",
	"j0OqHJj38aNHtQKmQXLE/f+2KiVz7fuQIpgFLl4tL8VPGgRfH3y7s/m8hNTM/lWAc0hZ4YOkxpqAl+CQ",
	"X4WexpNp9QRs4kvSegY/2wZaIqmdBWRLip+B6wUn71LDAksSyd8dGVWLMm5pwFToxiuCUzAgu/ttqtb/",
	"4cImSmDWqcbbO7wM7YdzDjuBbcCNeHRwb5NSVk774S7idPK3ewH0iZV0jYT1VAguBmNBUrpoSOOi4WQt",
	"gwsZUVEeATJYtfp3VN2sqvhh+rZ2lZMPclkt1bqXO/qGYYu6xGLGV/cw6w9czGmaEmYu5n1MeWZe+jfM",
	"mwYq97L17kGMU5QcgzLkVtdO9+y8dJ2EGhKtWDbWN9RU2iTndK6FUIPYazRsIvYg/6Fl8GAEPQDkWDKp",
	"qlS90QOX8O+BTdlmLTW5IFeQQ7KaD8+9ErCg8pHwCSG73odpLN2QzUpmIj2UoIkq09iB37LNU+iyRpls",
	"QlTYtKzVoszkioiNTyYaW2hWSZB6f6s1blRTJ0dB1j2bdEyD+JKgB989mKIH3+n/h8pB//bdA1fVGzLL",
	"HpjUsgfTS7J5/G/mj8dW+ortFGa83U7D6kth+kJz8fwmw6SKZcLE8zKBJeSoMtn62i9apTuii+oth9Lf",
	"ZtBaZkooMbgirFHeqUQcCCsKckEChFpvBl1DapkSTr3W7TvleFqpCOjaO96W+3jHvscpcg6V44P2UT1o",
	"OY+ZYo5N/nc84FVrPmqmc5ebrV3A9zzd3D0CGJCVGgolCnLTwMSD+1pIDNDpiIp3jYpfP/r7faAifDnm",
	"bJFRo3v76EnAILFr/0/97N10SV/m9yrJQBYBUIn6W4ldQzQVYfRLP7XSvJhZqX/YbYUw+67bigBVcvHx",
	"qTE+M8nw60df38OUL7n6gRcs/ZRlUUGwyQ1eMrlJB3pV0fEZUfeMi0tbOPu9EXE6KRj9vSA2JTI88h+G",
	"4R7RdUTXKKeNVRIv2pOsbslpQ997xtjcp1Df1eM5VBbYg6n/c7vDrKQGHiQJfGASMQoBfyW6dD9ixycl",
	"cEwneRFlXCBndY13OR7Mu5ya/vdMDY2TyQchh/emGvmgBHHUzIxEeSTKH5UWaB/nueA2y12Ulh9BA5ON",
	"hbBNF3fbZGqNK2BrhyM3+c7oualNFC54pOcjgzvS0o+Iln7aenXrJjrAd8n4//c7Kj2xI46658/EiGuu",
	"UI8LUv/t0c3KuzM6F43ORaNz0V/EuShyR2zCHLTI8BJqGZu6iiavoV7Neo3FphotJmfon3onACqOgMN1",
	"WcQMWACSlRSJgPl2sCCuyoYMAcAhzdgDc5sq9/5BCaN66BCUCn1gB9ZDPYBMWKJoRf2gbeyW+QRCd2oY",
	"MvR1dLu61xf7JVcuVfzH+Gb3eFnVHu42lyqfifAuhEo7+D07S4Wzjvq30TPqg+FoU1wb4PP0xPk89SJw",
	"KLZtq7mqDT66MI2qmU/HJ6JPcIVw0n78eUbUzpBnZz5H98FHjpgzYk6f61Av9kDDneHP6AG0QxweOdvR",
	"GvJX46VbPHyMYXcIvbK+PDujWJ+El842Avj9UahR2B9J4kgS7069sJ8SKNMifYamGOn0Ka9KRb1RAwR9",
	"myqH8uMOFQ/loJ8EPQ2hMHJ/I6n7fMTGdpIjCEsJYEBHji9j8zMNg0ySDbXMqW2zS/VMbHJnWC1rEu+K",
	"/kxba1xdMn7N/EJ+dnkg48ZHaHxabTv5WJVHjw1y1O8ycpOPhGLkiT4cgSpTlneSpzBb63AN8pmrXDDq",
	"kUc98qhH9nrkrTEq0CrvDKdG3fIoXYzE5NMgJh063q1pSUXjuzNqMup9R+oxUo+PWzdBfMnlAYnHy8YV",
	"R+MYs1+Wcva5xweTEzww+tuEQkAZAoaolEU12w4Uq8sFv6IpSadhFn3rRL0iySWiffGJ1tdaxicBn2rw",
	"X6cSJVgS7+ZNnR7F+sjXIQIVanCW2dKauu/UFr3xUA4nMq7ysPI5MWX3WmMwpPhgqo/GwY807q9N49DH",
	"ReRK7IkGAzY+D4kLbNSl7w8RbHQZowU/m2jB2BXsChzc6nrpHtHLNYYTjuGEYzjhmKt8Cw5tzFE+Pljt",
	"D1Z31BzreLbaIugaPe4omK45zz3H1bUsYPS6G0PsPnp5aIvAu+1oQItgtK2iuX3KMTRv1FR8OtrYLaRE",
	"iNLbDtkqKtg7wbRPxP9i0FM8Ytzni3Hd0X3bYR10umO8G3007gb3Rw589PH85JPMtpC4rnjA7Sic9RS5",
	"Yxr3SXiO3FLL8EHI26jcGEnr6D7/AdUpt8jaHSHMkcryptcd0ONPLi93Yws+V/mHpstuIf0qn5FSjlLv",
	"x0Kxtg8Den8V1e18j0dF1Yiyn7mi6r0wMa62ugtcHJVXo/JqJEKj8mpHyqv3onptqqy7oHujQmtkgUYW",
	"aHdSyyIjZJDr/g+6Yb+7/g9mvNHd4zPxeIT70+OW33t1dCt/cUb3+9H9fnS//6tW8zmxQZ1tZXvcpoGu",
	"tK0EpzZNlzwzg3y4KjlAtka///EVJEN8/WtPYZt7P7S6I5d+M/Y9u/EHk47W7dF1/0OhZ0Pu2f8T/nuz",
	"r8g6z7DS7JGknHUKRKmrlpPwTDMPlDN4xOwQyI8Rl5DObbufy2a9+hEoO+deysZELdqQRUBFRi/98cHa",
	"QmwDlrP/Qmu+5yO+ztNRehylx1F6HIO3Y6SzRrdGEW58EbfkEQfEd3pWsf7IDeMN3/stvbuntG61Gzjz",
	"GDg6msY+FSZYEJwaDtA/f71o/IyoEYfvE4fr0B6R+TNH5sj7Pbz+cZ96NrBxb+vWUh16zLAw4tZf5qE0",
	"tY/7cOcZUTtCnB36oX8e9skRc0fM7am93Ie90G5H+Dv6ru8OfUe91Oiv/hez0vaVXe4jVdYdfUfE6pNw",
	"ON/CqePeaNPoPzLSwjF2Z+d6jL5oYtBalqE8Vf2lo4lxyex28Tp3Kp+NotEoGn1Y0aheAmy4oLQrdBrF",
	"pVFcGunIp0BHiuh7DNLIlk9yKMPsio6MkszICYwYPIzlNt6PrUz2KVGCkisiEUYplYqyRHkvRdMXyulV",
	"Ub1Exk1OZhcs6k/73Mw8ANv1KNZx0OO4sAvzixB83Vron7K0E+UJK9YaPrbG5tvpECfOBc2sU219LZxl",
	"G+NW60NBkVrh0HV2Sa8IM+29N+iduJruYJXGy7JvlTt3Ey2vm1mv2UIhmLNM9fkS358jJnmH13lmepjV",
	"PjW/AE5by9jhxP5YOqlqzMkcGoA3qglkv6KCszVh6rtc8LSAyAu4wEvK2XeF3CNYqr0DvQFKxHdznFwS",
	"lhrEHkZCAPlGV9B7fYFecoVwlvFr8vG8CPb2VZ4EQXIuqeKCkiH5Ek5d801/0oTTcOjRj+Mz8Tj2F2rT",
	"kz9h2FXSTWsXaUylMAbDjMEwYzBMLw0rKczI/IyvUvgq9eQziDxNbUkNyqZ3lNkgmOCe0xvUZx5t1GOO",
	"gw+Kty1iyzau8IMwuya+bLZVUkcmGT3jR9Xxp6M6HiLDGff4Qfj0jKidI9Mn4o3R/YaO2PQZYlOPy/og",
	"jLLeCDvGqdElY8d4PbLFo+vmJ++6WSdfnV7sg6iXdQPZOf36JFxBtpXn75dmjfqDkVCOhHLXugpr3dqw",
	"ZJiN1bQ/27BkiJW1bD2aWT8jhXZ5qXoNrcPukzG1Vm/TaGsdba2jrXW0tQ5g9krCMVpbx8ep+jj12lsj",
	"L1S7xbVsfGc212CKe7e61uce5abR7vqBMbhNmtnO9DoIyZtSzfbaochEowF2VF58SiajIdKdM8EOwisw",
	"wt4BUn0yhtjuZ3XEq88Sr3qNsYNwy1oi7wC7RpPszjF85JlHW8NfwNZQJ2Q9ZtlBdMwbZu+Akn0ixtlt",
	"Bf/7pl+jqmEkmyPZ3LVaw6bZb0uMoAUtaUYOqwg0BKyyOMKdUYkBFQE+T52zO8O30NWYdMyDVYhscjjZ",
	"n+hHw7auH/Ard5ImwYUmCIQpu4NZkAK78mHStEUFA3GGjolQdKFbkzO6ZJQtLXWrmmGdVbJsLU1r4Wlh",
	"9zwmlUV0UJPgu3eEp76eftcKm1X3+8aNFEmvVPro7K+PwiayoGzpUkPgRHApUUoXCyIIi49uQ937ltcW",
	"g2xHCTw6+kdqM7L7sQLSM2DbCaGw6wjdsSO6G3/z9ub/BwAA//9wW8/8Bf0BAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
