// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9iXLbOLbor+BxblWSaUneErfjqqm5iu0k6o5sx0ty0628CURCEmISYADQstLlqvcP",
	"7w/fl7zCRoIkqM1Kp2cqPVUTmdgODg4ODs6GP4KQJikliAgeHP4R8HCCEqh+hpShf93uDJGAO/+iKSIw",
	"xf/qDjmNM4HOoZjIShHiIcOpwJQEh8EFShnisi8ACYCmLhjhGIEUikknaAUpoyliAiM1SOrt52qCitay",
	"ChAUQN0PJUBMEOAzLlDSAadUICAmUABIZgDdYS4wGeuqUxzHYIgAvUVsyrAQiEgI0B1M0hgFh8HWLWRb",
	"MR1vwTTtxHQctAIxS2UJFwyTcXB/n3+hw88oFMF9qwExKX6HGFfwV6fTPe+ZMhChESaIqync6m8oAhrr",
	"gI6AmGAOmEUjlB3Iz5AAPX4HXCImGwI+oVkcgZCSW8QEYCikY4K/5r1xiTM5TAwF4gJgIhAjMAa3MM5Q",
	"C0ASgQTOAEOyX5ARpwdVhXdAnzIEMBnRQzARIuWHW1tjLDo3B7yD6VZIkyQjWMy2QkoEw8NMUMa3InSL",
	"4i2Ox23IwgkWKBQZQ1swxW0FLJGT4p0k+htDnGYsRFytCsmS4PD3wCA2aAWjGI8nIhSxHKz4HHysrlIr",
	"uGvL5u1byAhMJGX9HhQL8i5vWnx7afvuUV/xSZKKmRzorj2m7QpNNFJAeqUq+qhZdqHXFwGYpjEO1dq6",
	"E1cbkaOgFXzJYBQjEciBiICYIBa0ggmKk6XnrkA5yns0H97mHec1iv7Np9dqmDmTtLDLtogIOV8Yx2ej",
	"4PD3P4L/YmgUHAZ/2yrYypahxy1vhy9xjGxP9601OrhAMRT4VnMk2QNDXzLMUCQRodjLx9oeXmZ6J+T2",
	"HWSaSZVYFioKYBRhWRfG56UqNYIpE8QJucWMkgQRAW4hw3AYI3CDZm2170AKMeMtgIkEFkUgymQ3gGVE",
	"4AR1gKSnGzRTO1i3QDCcgCTjQnK7IRJThAjYURV2n+2BcAIZDAViaqNVcLECh8txc06ZqNO5/AoSmKYS",
	"WkzAiLIECjAIJpQLWXiYk7P8axCAx6gz7rTAIDjYPtg+PNgeBE/KDNp8l8cGFJJ/BYfB/x4Mop8O5f/9",
	"V51fLwE7o7c4QuwF5J69ekSThBJQrLicBYBx7O5atZt5/TCDBQdYmYwt97hvBXIbN5yJDgyyVr7mO//v",
	"//zf8kqDmJJxC3ABmQBTLCYAghhJHALKAMmSIWL6EDCLAggFU8mueQpD1PEehe7WspP9uA79mDW4TFGo",
	"ZorlTBNMoKBMfjBUpMUQzcQakGl4nNN5iW02tjIVyu0Ui21oIvliubZl0w0NDLN129znFDM7VYucY/G+",
	"FVCC1mWiHiSsxUu9IK8Fjwe9a/VUxfpSrPvCyBVvcIK1WFsVU3U5iFUFtcU9B3N5c4dp5mEX59e6E8nv",
	"JFi8A15qtseQ3DiKgQ8hR5EUXKs8pMzstjs/P/NxtAQllM3qg/fVdzO+2uI01acRkGLZAyDZfbafPEgW",
	"ri3FvFUIKeGCQUyWXYo4X9d12GwDlaw1vUsBRcb9Yp8uU9I74JiM4zL/NveYCN1izW6tHHjOUAqNbHcp",
	"2bf+eZERon+dMEalwHZNbgidSk4k93+MBIqWlw/LM3DHrBU6QNTKCqhqRRbMWkEBd63ImcgS2L/miNXl",
	"M5aRLvefnxlHCglWEteXSPVZ37zcBTIXrCGSkhfISISYlL0wB5gDQoXuQfYG9X1OdSP3ISbqMpqfQtwj",
	"+YPHeGT/HsboSQccoxHMYpHf2wxUUA8Ex1JaZBnhcrjHY0QQg3E8A4xS8QTgkQKJpyjEI4yi+vldvstc",
	"G0y4n9v8Bqdty0PaKVVXxuBQsAyttTve0TjTokxxQSgvyrG5DkMlzkTgVrWQU4/AcKaUCPMYgV9Suib4",
	"S4aAu9Buv2aFPFymxnkZCmOIk3Ma43D2UH6jsXFR6rIqVKkJeSSqPx4iHfQSOEZ69JLgtdaB3KcZEZvq",
	"TEHW2OPHpQ57T8saS9DL72EKbzAXikM7G9NUlgSBBUr4ZtY9KDYQZAzOggfsqIsqWUaadahDVbKcoNWw",
	"zyZ06nCTCSRRrHaf2R/TCdIbg04lVy+hRemlEnqreYs9rMx4H9e4iOm5aL4///TcCFc4rbGDhi0/QgyR",
	"EPkEFlNkOXSE0pjOUATOjnptSRkxhkQALKla3rLksTmCoQBDGN5IfM4d28cKXHjWuWjxyyxJIJstKaeU",
	"r7m8WUZ5jWAsJrOgFRyjMYMRirxyySl1YVldOCmDXwzaWMWBprGORy4pV/DKJ+Uq1Yk1LcWRpMqRrIcu",
	"8VjuqQv0JUPcoz1prFqog+VOZeajUksAjscERSAs2oIRo4lataOuT0PhaqnX4Gp58/tWcINJVJ/Hr5hE",
	"kllAoBfZqKjySdh9cHFyeQWsBlhLX5qunfkW2u4EzgAmIyun5ZNEJFJyivojjLFkazwbqmudQZUUqDrg",
	"CBIpIA0RyNIIChR1QI+AI5ig+Ahy9M113Upl1JYo4x3/JU/ACAq41rqcKcT1kYCyK27OwNWv7U0kaE74",
	"gOfMeoN96z7r6qWc1AylOTgyc1yaI86fWI2E3zOYpkjyb5qRCEAlirdDhiTdgKPLixZIaIRifZW+yYaI",
	"ESQQB5gqeoEp7jhbkndudzpzQahvVHSXYqYvRiikJPLen1V7rSDOLUW3MMYRFrP8Ju0AIofRStngMMBE",
	"7O0WlChl/TFiEoXoTjA4T72di0U1Ki5LODW9t+wYQKH3D8qvRcVNx+JY8S+J55SmWaw+DWfqa/e8B7hi",
	"ChL3qr6cOZRMJ0kyIS9THi23Ji4v45UXwyHkaP9pG5GQRigC5yf94vevR5d/29mW4HRAH4pwYsx3kgQ7",
	"OTvGKI6AvPi59DCPp2vGV1qS4UwgH29QXJ6desWaHok0kSmYWE4Tuo3W8Cpu/CWDsboaqouRHDfB5A0i",
	"YzEJDnc8o2bYw92ve8d/wqo5QHA49gnu1+p7ft9Vxw1SovwNmgHdysGGue9hzrPycVmS8heSs9UfzJcu",
	"/wTEVJilpe0SqWyAOzbI5gXNwTRl9BbGWxEiGMZbI4jjjCHAc5kyn7pjauANiwHwqLDie+wrTlX/NjZd",
	"1qWiVoFNQKUEny/EUhtQcmCsRT2PxciWadlZLjd1N2MH/CrFSRA6FRkCXYU6FLXAMSJY/isx9BLiWAO1",
	"/t0zh8h753TpxpnX8tRStzU8zALcZJtbS6PgMeA+tJ8GZcdDFTJN5rD1FCkkxqS5y4/3KyyvJZ6HrWre",
	"T76WqcdE/pCOtd2sQtHCb5L82GratQVPipCAONYmCEoQgPJwEZaHhRlj6nIhJKOynjqSfV/kR/lCnPpt",
	"zvJrwR3ktSlT1wgwonFMp/LC9GshU8gh3bsFuObIGHjlailPqUgKreZsDLXvibxmeywpkIsrBgnXGMVN",
	"hmdZDwicII2LHFaRt0WRvpRJzBnuLyEhVEwQKzFZeftqy7781yAuz+46FK+zBBLAEIwUEzf1ANZHkcSR",
	"XT84pJkwEOfgeYULOlRHb/RKKdOF13dLzr5jLx6dcV6z0MwX2JhCrqQQbWXLUj2sK3HvP/VK3AxB7nUc",
	"A4+HDKPRE6BrFEK9HfMRX2qmD7m42aEaLmqm65aPlvKZFQu7OiNarCEsYaSlSJCOwBXLUAu8hDFHLWB0",
	"Oq4OS5YHrUBVcLRWyympKtCZvipfbdeVz/lIC6fe4E9mfMkKwsOuJsOZopUxglZwdd5/h5i6AGjFli3Q",
	"0odChBQ96lXDEHGOhzGq/mEZ3zlkXFW9nJFQ/XgnL6GyhmRgmejJ42jMEJdkcp1G0FgT5eFkq/azWOA0",
	"RmdTghhXcN3iEB2jkCYJ5hxTY2d8QakIJXWxI6txXXLNTgijcZwgIox862ChVlZGQqOI7HTRWCfHcGON",
	"HPWNNcrgXKCUciwom3kXRK5DY0Ft1dzCfAVfxggJuzbqD99a6jVyVlR/cNdVf1l6dfV37xrP2S0jPK4a",
	"gB4gnr3CwtPnWnJZcW5fopAhsSlJb1PwvRYi9fU1D9l1z57/bPlfeRl8o0tEWRpThqMl7E7awKRlAcwL",
	"PwPv0Z9S5vOBcp01N2frVI6hHsUJc92ANuG0U5dDNPK8ov+SAkea2d77lEjuanlJQdzl9Up0tcVe34WZ",
	"gwLTaLFSx+3d6xKwhqt0fXpztjqj5OQulazeKxnLcoDyCtbdV5KlhCLKYmXqwQninQGR6DA1MAef/g7M",
	"/z4dgjboY5IJxA/Bp79/AonRsW63nz3vgDZ4TTNWK9rdk0XHcCbR26dETMo1dtp7O7KGt2hn12n8HqGb",
	"au/7nQG5zFK5dVAE5JJDQSUQbVnxMFcDQzIz5i3jySy7wQRMJMh5f+gWsZn69kSO+6n96RBcQDIuWm23",
	"Dz4pxO3sgm5fUskB6PZ17danQ6DcFGzlndbOrqnNhVIa7eyKCUgUDnWbrU+H4FKgtABry7bRwFRbXGr/",
	"tPJcDgqUSK5z4DQZkBPtLCgxB7bbB62d/fbunlnSztJ+2UcZFzTRh36PjOg8q0P1aqSMMjqeJgKh6sj6",
	"bZtV8cJR1SM7nWCiKVRpYNUtsmz9Xo6P6NnUIdbfy9bcdDLjOISxa2K3Xphla21TNIw2wprOg7IdMYZD",
	"FCvcjaQEJ+/exlEk9zIPRvu70Wj4dPQs2g2j4fD53t7zvf3d4bPRzsFoN0S7+wfRz8/2nz4fRuHB9vb2",
	"3mgbbT/dfb4Lf0ajg3BPca0fNuYfNuZluyluCA/US5iO1rAef1xtJ9ecVOv+ZRsK/EDJEEUR8hD8+wkS",
	"E1RzjZZ7wDayNq6hvDtpEdEhgiGlMYKkObykol9znScXe0nCaOYXgHSciVFWWGfY6QSHE2UDUS3B0s6Y",
	"KpjFcxac5qPYOsCq9pocyj06uA25DWMOWKa854zLcG8EhjEkNy3f6rGMWPdh5Uqs+jQftJNe1dV34569",
	"D9qFfl/4+1azy2WhtjNVcr++Kio37IFpWcUCm1judyeJ2qG6VqHpzPdpa/UoqBpPKTuW+QQdritY6pso",
	"N7iK16rHV69ytzTS1dxd7wpAWp1uT1KlZC4FjXwzhfN898UG9fOK+Nc6jyaUHzm2nkLDrDErGdkIj+sI",
	"ZkhudxQ1RoFfmAo27rux30W2/vI4q8+c07hRPDXFrpRqtOvqc0gJQaHROee0UkcG13fC3rGfoZpi0Dt2",
	"LRqVEfx0pVv2HUmmsl3y20M+ij347UEj4TaeIv8oRdyGkCjhjWsbPiZYYBjjr9rqlYdwI5ZgAuNWDrOg",
	"tlkLIBE2rSGMzkg801y3QsSVWbUcBK64vq5K1RcyZlChrzfQEl9UVsTmrgu1hRWQjZF4gMDmwnelOvPb",
	"cfU4D5i803n9DMrdhvQG5HLYGhISJCY0Km9T17pyTZCyGijbSSgom10gjpa1RsyD2Ol5XrXyqPNR05OS",
	"DsNidjRB4U0T52uuW+UIZd6IbQsQyiYgRUzuMu0gueax1PYeS8W9vDqmhmjTp1EzRjZ4HDV2v8DouQLa",
	"C6K1zu3XhFsVl2v9y81Mq5CxbwLFSPPquDA018uha65SwL0krhvtykbcaqLwGj9IK2oqNUok7+VitmGa",
	"k3S0siRXbBklxRUzWSDDydo5VuvnOE6kaJykFiGVzm9Vy0KSX87/Y3M71cSu6sW0txKRJhtfkc1ygDrY",
	"S/OAxoPKsRznG8nPB9ba85X91/KXN23hBcyizicW7O83eITCWRijtaT72LbewA2qqkIuOv+mZ1UFARs8",
	"pnw9N1Gnm/DIh9v6eaRdMAyJ1P0Cii8r0mkF6iqlVYpLUHjKm1wW5lRbTLNn3B+I4pYCXTQ0QqsWkMHZ",
	"ZX6DahSx/Fblq1In2qSslVwMXF+8WXwRbTK4LprpOtvy7HLpeb0r367t3Lx7TZUc43FjXEikyqp9aQsZ",
	"4BO4+2z/EG53Op0ny+KrPOiK2MtddVbCYW58XyS6mBQna/KdMnD2xI0wv9l4p0VGlA12W/WNT7MgH8nM",
	"40HLNd9NgJf8BPQClhPjFeGv7yEzvOeIYYFDGHuib1dhkWVA3eDeemkxuK/UAchXbIH0lS10i3RMRw2c",
	"ssInYSOlu5rT5bICpMZ1Z4O+MmVnoJrPjFYINkOnyzcFmNejzAcTpzFqsJPEFm+hwLeFSs/osh4IYFl9",
	"6Y01LJ/Mm9FRKT/xh0BszvaqE1RFayknUeIAxvvHrLIJ8HwgCiv+Pz4katNW1KC21YUqYA3L86TszlRx",
	"joIinJzrrH1es4alFlURmPx+5RnWLCHaTcXCkREslMzSMumvdPodKXXzbDTCdy2go+QnKI7bXMxiBMYx",
	"HdrBFPxqdDiGmHBhozziGYgpjJAeQsGUwDsbLLn7bL+Uj/D37fZz2P7abf92OBi0/9UZqP9+Hww+/q/B",
	"oD0Y/H0w+OfHnx7/93L1nvzz8WDQ+V1X9BV7sx4uTi2iXRIekMrGcfY13WjCvl/tUJyveqwrG/03Ku6k",
	"BzFMHpi2CVSaDRxrI2ooMhgXYTsPPROMQFpKFOUc1g/lb3VnA88mhXUL2WaGrNgil498zNdLZ49Rxndr",
	"l5Q490ZQuUvxTaId3TN0/fOmMBQq5ZvRS2xORWVVbZcIkWWirwwF6mAjRGwksWHK4PHp2dXJoTam5+5w",
	"JmMZQyJjpBR9/GRJ3ZzxJvjMKWnjMaEM5e4D+b1+c0qLTZy6eUcPcz723rzkSfngjVfbbPpcs36Q6/Za",
	"dDLvPLf8rHSWboaTaQiia4JFMw8zHnIPPomiBjWsw7hKiC1zz8DPTF2acfd8zlAUdRaTKKjB3Q0r3hbX",
	"9wNxuMIEsmgKGVJ+wdpxGZOx9VgqJVzfvH+IgcGGf34zDxEPvjao5VwpZZZf4X6mgnT82bEu0JBSEy51",
	"TqeIoehsNCpp5LtTiIWK/TLeEDqGcBTjUJzDjK+oAC1NyAGtVuZA6ykt391LRe6cPMWlaXrKqyrZUqEP",
	"GZ5qVfwsWOMSp13O4/zMJtc1m8nJY4PuUsqLY1U57nUG5ASGE5WPJKSMIZ5SEumo6OJWp3eVeZkhhCkc",
	"4hiLWWdAFvuu60mUNmVI41gnjc+9lxvFXQlko7OSFDu6yv/QeCt597DrkNzQh1NDSok6osLgqeZZX/Qs",
	"6cnnPfSCUgF6x6t0pUMD1j5VayEKUjSxjFUvgX/qZzn3vbTcd0mYq87MLpZz1NShaJXXdEW2V7vYLfCa",
	"SVVNZX1IIIFjHYKvDgB9LKonDMI4i2SJyixpvjuZdSM6JeamLQ8sk0DFY1Q39S51YNF6kqaeYd5FLoRs",
	"tNP7dbAerWUU0dBv1FDpHuO6+29+jJcwsMFjvN7vCqbKArW5nTK9osdQpQc6y8TZyPx2Yp/XUbyXgHSG",
	"8JS6o3obV4Kwy6ULdeuY3yyMftxMwGHrLxZG6WVyRrWjuJvuQPE3zG90crFVXrKKMEPKUS9/ysoqd2X3",
	"5T7nz2XV52yOs3lpTRJ4h5MsKdIHwjimUzdmQnv6CgpCk5ddPz6TNygYeZ54HEAV10Yly7g13imImVQ2",
	"Jn+v1mXoNwqKMMv8o8qPdQg+cR2xyHUCxBb4lOgPOghRfpjoDyrcslN+JObxPw9/32k//zgYRH9/8s/B",
	"IPqdJ5OPy78Yc0JCKk+uZRxIkamrCVW5D6uVhQJW3vJyOUoa60zNOvfg0jks9FDnprH9+4XppHk6lfwW",
	"9TnVqsxJPGvSvknS0J6qJWXeeiGMdRDLEWsmYHFnL9rf240O9vd+3gshRBHcfxrBp9vPdkfPn/08gvDn",
	"p7uj8OftZ9vbu/s/Pz0Yhj8/395/Fh4c7DyPdobbbvRayFlwGLTlfy9OXvVOwdHJxVXvZe+oe3UCLk7e",
	"Xp9cXqnSAen3ei9efD56wd72XnSPX7zpX99ML6Yfjt+9fXt8st296+++3e1//eXm7PjD19Ovp58/vH8Z",
	"//bqZPf01cXk9Li7MyD95MOz06so+fD+ZO/0+Jfkw9dwenrVnfY/f9g7PZ7gD1/DZ/3jDzsfvo6f9q/i",
	"m/773rT/8mZ6Mv3w+lf6W29Avn7ePuq+/dCTf339vH3cfRsevx13T16/6B/tbZ9e/HL1y97p+7MY4ecf",
	"3t+86G/1v9LT41ez/sWv2deT7a0BCX+9mf3Pu1/Q3esv23c9srv74ej0dO+349O7u+n7/Tfx2/Ee/vyK",
	"3F6Kt2fD/W6336Wvjo6+vLrsP33+ots/GpDu9rjbP7k+6r09vmR3eP+GRUe/hm+OJlH/xd70596X5Dj+",
	"bXJx8mr4un90cvmO7HN+3u2Nf3vz01v2i5gOyMHFT+xpiuGH299uBOM3e7OjXvZ1b9L7OaYfkv8534sO",
	"/jEgCu0np8dzluRH7OmP2NOVuqlxmA2Eodb7/BPyGTdkMoLxElzdVi0S3/mvAjmPdyw1htmrh+saQ0Sg",
	"TYk0J2/o1IlntQfLBHIwRIgA24E/fLUIal/z9b2uzRSre1IKmTSNZ0VW/4Z4//oDaHqeD1+24vr3AGG7",
	"mSjqUu4CSBbRhmN9fSiVdBs875Q0CIUJFnbpZAp5iUSWcyy3LV40RSqXA55lXbbUI3i215Y7pSUyUC5a",
	"gjVM4B7E5wvUWZ4q/dofbzV9EDoVNTi1uo+49TVV1l+P6yFn/nXxpeJ2UwZznSbNJTTP/i87Hjww10Ar",
	"UJfpi0UBn1eKaOcGfapz3sSfdT5zSsBjG6X9pCEmY9Pcz6axtPZj9WiywxAxzy3OE0SAFDwcMsPcx64b",
	"OKZc5PWZZZOOrKHiahuo1kkTx9Jn7OaYs+NqsSi7tbsV6imuOysnrq5ntEV+PPxVU1G7bwd7MRbqQr3E",
	"I+yL6gjntVdXdCDQnQCPr69etg+eAMqqjwU4g6joYhw3roWsZ2/sa5KRo5VYXtcsEdUcMi1L8yDpOobG",
	"jGapHz9yro84UDVajg4IYSXdQfuwm3lyFjEcgt5x+am7QcAoFYNgbl6LBQksEhqhuRCmiBl/TvVyRwd8",
	"oJm6c2mYtT0mkTekEUxwjCEDNBQwLl7OhUrB8xUxavNjbe8/faroAeozMMSJaaBDq31tnu5uP5GXPpHh",
	"aIsjMZb/CBzezMDQKL5AHumkUoeUXvXTKUQqk1EaGTlPyagLvErw/JlOMvNsYiO26FQ9HfEN1/ObvkAo",
	"6XkDyusHv0xe2nXrJZAcchpnYs7b5jlbWUUt7E9wWstqNMbiQgLsl2ucnJQQvMKi7KlsHrVYRU1uleMm",
	"G8QIj23ChiLdbUNiIFu8WLQvuio9wVL3p1XS6gW6xfNkO10qgc648/LWXHhr6Txy4GujtpoU/vPeCHdn",
	"WwkRWPrRObPySx/E1Veav11C2PUSpoYTyESRMHWC4mRhuimlck9hOD90Lq/lSzRlHgiU0lT5feVk1oZp",
	"2i6G8Iyv1IpzJH2dRaTmketsQd2DNwOWNbvIE2eIBYMMxzNAzNNB9gECXlHm5+h2d1xAxpjcKeIdB4fB",
	"Tmd3RzvK6iTRh38EiMBhLOlLgzyhXHBFGfJXcGhH6IQ0MSSvizWrCLbMR22JCc4ZGuE7+zooQ2pSRzST",
	"MtxeKzDXGMVqKBPB4cF2jtyjOOMCsd65X3TS+JJce47/t0WqOm9z1VGUaftgsd5A9WOynMVQGcPU1FxH",
	"B/VglA79YBFiYIhGUgZRmS3Npo3MiKWl+N3AKitFmc6WM4NJHNhJtOktYgxHiHdmSSw38rKPHG06q25D",
	"hunaYTMRIl3ytCHg9dXV+ZLnjVyoc++ZI7/aE0bfcB/pdbUOXoI62icr5VddqBUoHN0i5lhDpwwLgciD",
	"TytWP63sYWOTxs1ICOacYzoOxjd5lt9Yri/emOeqaCJJdiSMZlZedFQsMOgJlRxJ+/Mg8CVDyprNYIIE",
	"YhzwLJwAyA/BINiSVL4l6JY1XfxT1f6Hqu0TC+eeiPny/fmHoKXIpUl97rM+c9JIL3uKnR31PG/L+s6d",
	"FIY3SzkUPHh7z33BuR6brR/yVYJSMZtENkcRgM5NR/HKOTHfD3kE+1JtF2WU0sfGGt3pntTEGwO9de+r",
	"ofI8i2Pfu8690SkV51qfVXvd2Xqmli9ij9w2jzrg/QQRpfyTZd14Cmf8UcvJJ485SLM4ltc9lSNa4ARV",
	"Wp3KklKjJOMCwFgn8lTvtjWnHtJjBq3qZFSvS/o/SPzk/cg/Kn3JT6a/uXj2UyuhQos3rvtQZh6f+IaU",
	"+LDMCvUOPcF1bu4Ic5LQkTxLF7xd7bnBlUh0vek7ZL7Cm9uLodUvcDI0xlywWQdcSXE/gTN5KMMiB63T",
	"UD9QlbuYSa5kO2vJQzamZCz/NRdcyhJe58fcdRpb5oRb+U3v+Q+8zTtctL//nPhb9+AwUs7GYtwL/ckC",
	"MVND+ZCDqOldlMPVMZIL9/r9zjpHWx83uW7KExL1bcWZRhQ3IHTu0zU1pG4KdnmBk6Mtq3hyHsbTDf9N",
	"9dcZEWveUko2co0D5yZiZKtGDcfiNSvQuqqKpNCNLO7q31cn7dlqrl6nWNqPi8yjpnWxAZbeq32VpebH",
	"6zUuSpa9k5zCBEUmF7neLmXNgpyqRy40MlpNLvw2V4oVrxKOv1w9jC0vkxJ/nhtZKQBgHIMUMY6VHrDI",
	"G6Wk/Am8RS3Da4wigKsWGhiVx52Zuvrg9NjQCaGiSLGwpg9DUVk/t1kKgPc/1GIe1s6TVs5xOtIZDJSn",
	"5hRy+4b38p5GEYrROmPhOFYhUbL5KuON57xe2gUcfcnUcWmeYij5qTqPxDovm+YuKjotsvbYAefVp8v1",
	"+dMBFwhGbUri2ZKPnS52YXFyrezvLQyD7EOVgtR4496gmVaxGkWtVmyVE3tTNoYEf9VB0iEUaEyZ/PMx",
	"D2mqv3IUo1A8sbTtJarlzk9dv5ZCxjcvdcb5FtFxI4ZCHoVcGzLs95aUEAbKrXRLjj0IzFtbTQ9pqFaN",
	"jktdAmgKv2TIIlUNi1VK2zzoQStcH/EifNVxcYLEmXf9oFiOi51DEU6ccIVc6vbTzUi99FphOLRh95nY",
	"SW28M2mTXV0FjKJAWxf0Mc5QQm/V9iun7XPe2fOKb13wy+XZKTjXUkOu1fJbe/ygav9y86wzVTtYAtWp",
	"HRI0nWcxrKdG8aD8bQajGIkfjzv+eCG+kUYujDnLf1+5KMcMGcuXurD4VbpN+6be1t7D7cFzSoXhiJAY",
	"5aNkVqq+PU3pLWKONaYwwXIWbmESobvOZ/4AHmWF0m6MmLgwQcRpcxaB+jwn5Vz3FV9apdmXffsdWxvj",
	"+2zkn5TxhJU2JDKcyyK8RQyOkQ4+BNh5NMnYIdXAmIw74KU6TQ7nx/U94o/KAXuPkkflgL1Hk0eNAXuD",
	"QfRTc4xeiliIiGjMZFuUS6zpGWnXVobHYymX+jCpZSKtdbhFa6d1KhHBpenJH8psh3HWrjS5snDzcS0y",
	"LEFQD100pTXqskefN7uoynywnIq+EZai48YqzoiNdTQoizBhcxzK+WM5/wQTaD6YZ2/lz6Pz66albngP",
	"thUcq5S2/kZNcdStoG9y1vrbNd/gixvm7FRHQLpXayk1rn/MNExxrQNm3gzWcblvQKQ8pxr1DEsSxdz0",
	"Fv7Ib1hyF6tcai3vn5fYU1UCTNbqgDMSzwAlZvNJ5gUsZ1Ae9ZqnbibZZ3Ey+dJ9yuMQk3FPSqfe+LH8",
	"IBkiMUWI5LHrqqmczJ9wNuSR3E0HxBzlU8tdH8+Ml+axje+F6DACrAUekTHjeaVmE8LYBllElDyy/iNA",
	"W52c2+U3jGMNvd7Rl9l4rP29lAuLgSu0DsXqfqkjJFpgG2DjiazVt+4tf2/Xe8v/ETy70eBZzr2izzLi",
	"o5s7RuLR3nyb3vLkfjk1geEEE9Q41HQyqwwgF9pYLgbq4ZGMoUFg374APQOQJgH1kmkqlGqJIZ2wshy3",
	"cwtxLAfugC64UGCCMIZMaySsUxi38YsRAsNMbjqkU19ahziAxYI8NvNSvRXIA2dEipqHYBBcZmGIOB8E",
	"8nbuzPSbkw1PUdiGJGo3PieyRBBy/qqlYhM5BRREtzyD1Hkfuyr7t8QbarYtTPB40o7lTHXmSZUyvEin",
	"W/Ib0enEFWgxVTEVypyZfx7Zl2VsJ6pChEp/JlAyJwKJUeeMGOITXZStlLinPsuuBaRedOFAXC/tFXOo",
	"F+bv5TQMaCdWLz4uz7xeoV/ChQ9qBzv14oXJhEyTE+X3u4AQtHNwOQhNUYSNo7JUYL2IW/ZXm2XE6MRj",
	"TG5Ukf7hlMAYQ66Wn+sa+odTQ46MQ/3Cgx0BE52zJ8i16+qzToWlHY2GMHJIpxWsRj0Oak7yeTWWXeTA",
	"1qu8sVNvKprXuGuwUy/pW3w1Fc3r9tKitF50XCC5Xtgr0F4vfOUshIfAnKWpl76A/lZF4kkP7uVptJDG",
	"31AYLaBwyQGWoG8usqGkYGoycBIq2iOaKR49hFGbI2E2NDKJOBPExg5Nr8vJ8ilcagiqn99YiKoFp1S8",
	"NABWi17A6DKHt1poE4lWv/ftfGoFFWLMC5blRE4q4vrb7QVje0i24+qpVzVTeQ/BZtnNevWqJFklxeVZ",
	"isjl5WtjfwERRIk+rh3r0vbTA4+IgwrifshMq2z9XhPtg/stbyXluz7MO/Vtq6kWIFoKScZXw5ozCyEi",
	"RxzLCLGyQGFffFq+aML21+328/bHn7xaSDlQwxPx9ikKG+k5CDifRB1jlB4ETyrqZ6dwodimhi3TU3k1",
	"3RVolSjaweLSctwVTtBv1LrIWQ/kN1Tr5eqvQIKvlKDCPMi4ufkrAu51T7vGGAm6FyfdrTdnR92r3tlp",
	"C0yVpC8/ljONSWkYExVSzQANESQtZZO1LXMnIJVpDjKBwyyGDHAskIq/VZcOKABkCLbUVjKIB13lHwS3",
	"TtH0Xx8ou2mBk0xyg61zyLBVzGQEJkM8zmjGwV47nEAGQxUSYedaidMFjwfBq/7VIJCrfn11ZBZ7uTxz",
	"17UUpFXP3REm1uRqaukcbJmg8moU5klUlZ6KRL70qwInttR6Mqnp0MyX6GA9/5UjRsnJnVxHq3hQL+e/",
	"YjBEbiLC1VWBtvF9KxAOba7cUU7YtXuRCLzQLr1lXN+d+qPbdacivYLG62hZm5juJ3UcAguHZhWnbihS",
	"da6XuRw2FmwhEW6peD155Rx1okNG1006ee88RavgCNXUUQJxHBwGAsHkv92Ef4F1mFD88qUqAUfy4ktj",
	"cIVgIuUXJpvaq3Kpdc3t4/dyFx8f+5o9Mcomk9tEZWVEYQyZNi2qxMUoMdkbRjFCQl31UTS23pbamURM",
	"EGZgStmN3Ghcp+eOcYgIR05uwm4KwwkCu53t2mSm02kHquIOZeMt05ZvvekdnZxenrR3O9udiUhiTeRC",
	"LVcFSd3zXtAKbvN0ijaDok5ILekwOAz2OtudnSKM8o9gy8kRYpLlWN2XDpL05YI80o7PEBwVjS914yI5",
	"ZKEPz9UivShv3Ngy0OSFuHhBo1klB4fjjL712Wii9J5ejyc1AnFfJnPjiKuztHO9C3e3d74rdL4lieRq",
	"P93e/raA5TnsalC8gBHIgZSQ7HwvSK4JzMREOW4ZpOx9L1BeUjbEUYSIhuP594Kj/BKCAmb3uwFzRSno",
	"QzKz5KJyHD37fot0qc+Aa5IrkrWbBxyry3Ajlww+ympzuOjWH5L736tQAyR8HjEw0uJb7rveuPHrzPQV",
	"EvM4aRGDqyzA810RFzNzICgYaxsPlj2YHCPmeDMO6mWu2XKWq6p0yAj+kqGetmFqh/mPNSa7/Rdisme/",
	"/uBqDVzt6feCI1cz/eBnG+RnRro1zGvL5ils5GKvkDApCUxCQ5MUsFkMfIWETZGo8yeuyq50K8OSyoPz",
	"qq/GZjjWfT1Tav7+ntI05hC8K17FUcOqHAfFuN4EkfPG/dPZolmSRh64qzd8dSsCJ6LzL8Umvyd7AgV/",
	"+n7C319X7HO4kmYafhZUWOBTKEJ/KKQNc3Qydx4v4kOqWSmD63p8yJWRFISb4jkfV7kQt9XQP21gDUvh",
	"FUtdh78zS/px7f0hIC7mwD8kxIqECJpExJwZt4I084h81+YBsFUZ7oUOUNowyy2e5PrTee4G+doPFvvv",
	"yGJ/sLblpboiOfzyZgYCfI9Pzbcv+J6L+tO2dH3wv4I9oQGqH3aEH3aE/5Cr5F9anqpxvkaOuMhk8AqJ",
	"VZniKyR8HHElqat5vI3aBb6DtmspzvhD+f/jbvcfzYvudXpsywy0g8oWTPHW7Y5Otadb11++N5yGA0qq",
	"dzPlYmQYgREE61r0cg/NfMbtrD6F+4/3/z8AAP//SoK7brDiAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
