{{- if .Values.alertmanagerProxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-alertmanager-proxy-certs
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
type: Opaque
stringData:
  ca.crt: {{ .Values.api.caCert | quote }}
  {{- if or ((.Values.global).auth).caCert .Values.auth.caCert }}
  ca_auth.crt: {{ default ((.Values.global).auth).caCert .Values.auth.caCert | quote }}
  {{- end }}
{{- end }} 