{{ if .Values.alertmanagerProxy.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-alertmanager-proxy
  name: flightctl-alertmanager-proxy
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
spec:
  ports:
    - name: proxy
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    flightctl.service: flightctl-alertmanager-proxy
  type: ClusterIP
{{ end }} 