apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-db-migration-config
  namespace: {{ default .Release.Namespace .Values.global.internalNamespace }}
data:
  config.yaml: |-
    database:
        hostname: {{ include "flightctl.dbHostname" . }}
        type: pgsql
        port: {{ include "flightctl.dbPort" . }}
        name: {{ include "flightctl.dbName" . }}
        user: {{ include "flightctl.dbMigrationUser" . }}
        migrationUser: {{ include "flightctl.dbMigrationUser" . }}
        {{- if not .Values.db.enabled }}
        {{- $sslParams := include "flightctl.dbSslParams" . }}
        {{- if $sslParams }}
        sslParams: {{ $sslParams }}
        {{- end }}
        {{- end }}
    service: {}
    {{ if .Values.global.tracing.enabled }}
    tracing:
        enabled: true
        endpoint: {{ .Values.global.tracing.endpoint }}
        insecure: {{ .Values.global.tracing.insecure }}
    {{ end }}
