{{- $namespaces := list .Release.Namespace }}
{{- if .Values.global.internalNamespace }}
{{- $namespaces = append $namespaces .Values.global.internalNamespace }}
{{- end }}
{{- $secretName := include "flightctl.dbSecretName" . }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $password := "" }}
{{- $masterPassword := "" }}
{{- $userPassword := "" }}
{{- $migrationPassword := "" }}

{{- if .Values.db.enabled }}
{{/* Built-in database secrets */}}
{{- if $existingSecret }}
  {{- $password = (index $existingSecret.data "password") }}
  {{- $masterPassword = (index $existingSecret.data "masterPassword") }}
  {{- $userPassword = (index $existingSecret.data "userPassword") }}
  {{- $migrationPassword = (index $existingSecret.data "migrationPassword") }}
{{- else }}
  {{- $passwordRaw := (randAlphaNum 20) }}
  {{- $password = printf "%s-%s-%s-%s" (substr 0 5 $passwordRaw) (substr 5 10 $passwordRaw) (substr 10 15 $passwordRaw) (substr 15 20 $passwordRaw) | b64enc }}
  {{- $masterPasswordRaw := (randAlphaNum 20) }}
  {{- $masterPassword = printf "%s-%s-%s-%s" (substr 0 5 $masterPasswordRaw) (substr 5 10 $masterPasswordRaw) (substr 10 15 $masterPasswordRaw) (substr 15 20 $masterPasswordRaw) | b64enc }}
  {{- $userPasswordRaw := (randAlphaNum 20) }}
  {{- $userPassword = printf "%s-%s-%s-%s" (substr 0 5 $userPasswordRaw) (substr 5 10 $userPasswordRaw) (substr 10 15 $userPasswordRaw) (substr 15 20 $userPasswordRaw) | b64enc }}
  {{- $migrationPasswordRaw := (randAlphaNum 20) }}
  {{- $migrationPassword = printf "%s-%s-%s-%s" (substr 0 5 $migrationPasswordRaw) (substr 5 10 $migrationPasswordRaw) (substr 10 15 $migrationPasswordRaw) (substr 15 20 $migrationPasswordRaw) | b64enc }}
{{- end }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $ns }}
type: Opaque
data:
  password: {{ if $.Values.db.password }}{{ $.Values.db.password | b64enc }}{{ else }}{{ $password }}{{ end }}
  masterPassword: {{ if $.Values.db.masterPassword }}{{ $.Values.db.masterPassword | b64enc }}{{ else }}{{ $masterPassword }}{{ end }}
  masterUser: {{ $.Values.db.masterUser | b64enc }}
  userPassword: {{ if $.Values.db.userPassword }}{{ $.Values.db.userPassword | b64enc }}{{ else }}{{ $userPassword }}{{ end }}
  user: {{ $.Values.db.user | b64enc }}
  migrationUser: {{ "flightctl_migrator" | b64enc }}
  migrationPassword: {{ if $.Values.db.migrationPassword }}{{ $.Values.db.migrationPassword | b64enc }}{{ else }}{{ $migrationPassword }}{{ end }}
{{- end }}
{{- else }}
{{/* External database secrets */}}
{{- if not .Values.db.external.secretName }}
{{- range $ns := $namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $ns }}
type: Opaque
data:
  masterPassword: {{ if $.Values.db.external.masterPassword }}{{ $.Values.db.external.masterPassword | b64enc }}{{ else }}{{ fail "External database masterPassword must be provided" }}{{ end }}
  masterUser: {{ $.Values.db.external.masterUser | b64enc }}
  userPassword: {{ if $.Values.db.external.userPassword }}{{ $.Values.db.external.userPassword | b64enc }}{{ else }}{{ fail "External database userPassword must be provided" }}{{ end }}
  user: {{ $.Values.db.external.user | b64enc }}
  migrationUser: {{ $.Values.db.external.migrationUser | b64enc }}
  migrationPassword: {{ if $.Values.db.external.migrationPassword }}{{ $.Values.db.external.migrationPassword | b64enc }}{{ else }}{{ fail "External database migrationPassword must be provided" }}{{ end }}
{{- end }}
{{- end }}
{{- end }}
